from pathlib import Path
import re, shutil
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'index.html'
s=SRC.read_text(encoding='utf-8')

def must_replace(old,new,label):
    global s
    if old not in s: raise SystemExit(f'{label}: marker not found')
    s=s.replace(old,new,1)

def must_sub(pattern,repl,label,flags=re.S):
    global s
    s2,n=re.subn(pattern,repl,s,count=1,flags=flags)
    if n!=1: raise SystemExit(f'{label}: expected 1 replacement, got {n}')
    s=s2

# --- CSS ---
css=r'''
/* v0.58 Project Pineapple — local cable surgery without CAD-style control-point clutter. */
.cbEditBar{display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:7px 8px;margin:0 0 7px;border:1px solid #c9d8e5;border-radius:14px;background:#f7fafdf5;box-shadow:0 6px 18px #10263d10}.cbEditBar[hidden]{display:none!important}.cbEditBar button,.cbEditBar summary{min-height:38px;border:1px solid #d2dce6;background:#eaf0f6;border-radius:10px;padding:8px 10px;font-size:12px;font-weight:800}.cbEditBar button.active{background:#183c59;color:#fff;border-color:#183c59}.cbEditBar .danger.active{background:#a93232;border-color:#a93232;color:#fff}.cbEditStatus{padding:7px 9px;border-radius:999px;background:#e9f2fb;color:#24597e;font-size:10px;font-weight:950;letter-spacing:.08em;white-space:nowrap}.cbEditStatus.open{background:#fff0db;color:#8c5310}.cbEditStatus.ready{background:#e7f8ee;color:#176c43}.cbBridgeCircle{width:40px!important;min-width:40px!important;height:40px;padding:0!important;border-radius:50%!important;font-size:17px!important}.cbBridgeCircle.active{background:#7042b8!important;border-color:#7042b8!important;box-shadow:0 0 0 3px #7042b824}.cbEditOptions{position:relative}.cbEditOptions summary{display:flex;align-items:center;cursor:pointer;list-style:none;white-space:nowrap}.cbEditOptions summary::-webkit-details-marker{display:none}.cbEditOptionsPanel{position:absolute;z-index:25;top:44px;right:0;width:230px;padding:12px;border:1px solid #c9d7e4;border-radius:13px;background:#fff;box-shadow:0 14px 36px #10263d30}.cbEditOptionsPanel label{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;font-size:11px;font-weight:850;color:#42576c}.cbEditOptionsPanel input{grid-column:1/-1;width:100%;accent-color:#2b729e}.cbEditOptionsPanel p{margin:7px 0 0;font-size:10px;line-height:1.35;color:#687b8d}.cbZoneRouteEdit{display:grid;place-items:center;min-width:30px;height:30px;margin-left:4px;border-radius:9px;background:#dde8f2;color:#274e70;font-size:15px;font-weight:900}.cbZoneButton.done .cbZoneRouteEdit{background:#dcefe3;color:#206841}.cbCircuitRow .editRoute{padding:7px 9px;background:#e5eef6;color:#274e70}.cbBoardWrap.editing{box-shadow:0 0 0 2px #3b7aa535,0 12px 36px #10263d11}.cbBoardWrap.routeOpen{box-shadow:0 0 0 2px #d892343f,0 12px 36px #10263d11}.cbZoomDock #cbEditToggle.active{background:#245d86;color:#fff}.cbEditHint{font-size:10px;color:#66798a;white-space:nowrap}.cbEditBar .doneEdit{margin-left:auto;background:#247b4d;color:#fff;border-color:#247b4d}.cbEditBar .doneEdit:disabled{opacity:.45}
@media(max-width:700px){.cbEditBar{gap:5px;padding:6px}.cbEditBar button,.cbEditBar summary{min-height:40px;padding:8px;font-size:11px}.cbEditHint{display:none}.cbEditStatus{order:-1}.cbEditBar .doneEdit{margin-left:0}.cbEditOptionsPanel{position:fixed;top:auto;bottom:72px;right:8px;left:8px;width:auto}.cbZoneRouteEdit{min-width:34px;height:34px}}
'''
must_replace('/* v0.53 — instant Circuit Builder reward screen. */',css+'\n/* v0.53 — instant Circuit Builder reward screen. */','editor css')

# --- Markup ---
old='<span id="cbSelectCount" class="cbPill cbSelectCount" hidden></span></div><div id="cbBoardWrap" class="cbBoardWrap">'
new='''<span id="cbSelectCount" class="cbPill cbSelectCount" hidden></span></div><div id="cbEditBar" class="cbEditBar" hidden><span id="cbEditStatus" class="cbEditStatus">EDITING</span><button id="cbEditPencil" class="active" title="Draw a replacement cable section">✎ Pencil</button><button id="cbEditBin" class="danger" title="Delete one local cable segment">🗑 Bin</button><button id="cbEditUndo" title="Undo route edit">↶ Undo</button><button id="cbEditRedo" title="Redo route edit">↷ Redo</button><button id="cbEditBridge" class="cbBridgeCircle" aria-pressed="false" title="Bridge mode — intentionally cross an existing cable">⌁</button><details id="cbEditOptions" class="cbEditOptions"><summary>Cleanup ▾</summary><div class="cbEditOptionsPanel"><label>Post-release cleanup <output id="cbEditCleanValue">Normal</output><input id="cbEditClean" type="range" min="0" max="100" step="5" value="45"></label><p>Live pencil stays immediate. Cleanup only runs when you lift your finger.</p></div></details><span class="cbEditHint">Draw replacement first · bin the old section second</span><button id="cbEditDone" class="doneEdit">Done ✓</button></div><div id="cbBoardWrap" class="cbBoardWrap">'''
must_replace(old,new,'editor toolbar markup')
old='<div class="cbZoomDock" aria-label="Circuit zoom"><button id="cbZoomOut" title="Zoom out">−</button><button id="cbZoomFit" class="fit" title="Fit circuit to screen">Fit</button>'
new='<div class="cbZoomDock" aria-label="Circuit zoom"><button id="cbZoomOut" title="Zoom out">−</button><button id="cbEditToggle" title="Edit this cable route">✎</button><button id="cbZoomFit" class="fit" title="Fit circuit to screen">Fit</button>'
must_replace(old,new,'edit beside Fit')

# --- State variable ---
must_replace("let cbScreen='home',cbCircuit=null,cbDrag=null,cbHover=null,cbSelection=new Set(),cbSelectBounds=null,cbView={scale:1,panX:0,panY:0},cbPointers=new Map(),cbPinch=null,cbGestureLock=false,cbAudioCtx=null;","let cbScreen='home',cbCircuit=null,cbDrag=null,cbEdit=null,cbHover=null,cbSelection=new Set(),cbSelectBounds=null,cbView={scale:1,panX:0,panY:0},cbPointers=new Map(),cbPinch=null,cbGestureLock=false,cbAudioCtx=null;",'editor state')

# --- Zone/circuit list edit affordances ---
zone_fn=r'''function cbZoneChoice(z,c,compact=false){const devices=cbZoneDevices(z.id),b=document.createElement('button');b.className='cbZoneButton'+(c?.complete?' done':'')+(c?.id===cbCircuit?.id?' active':'');b.style.setProperty('--cb-color',z.color||c?.color||'#65768a');const sw=document.createElement('span');sw.className='cbZoneSwatch';const label=document.createElement('span');label.className='cbZoneLabel';const strong=document.createElement('strong');strong.textContent='Zone '+z.number+(compact&&z.name?' · '+z.name:'');label.append(strong);if(!compact){const small=document.createElement('small');small.textContent=z.name||(!devices.length?'No surveyed devices':c?.complete?'Complete':c?.legs?.length?'In progress':'Ready');label.append(small)}const status=document.createElement('span');status.className='cbZoneState';status.textContent=c?.complete?'✓':c?.legs?.length?'•':'›';b.append(sw,label,status);if(c){const edit=document.createElement('span');edit.className='cbZoneRouteEdit';edit.textContent='✎';edit.title='Edit cable route';edit.setAttribute('role','button');edit.setAttribute('aria-label','Edit '+(c.name||'circuit')+' route');edit.onclick=e=>{e.stopPropagation();cbOpenCircuit(c);cbEnterEdit(c)};b.append(edit)}b.disabled=!devices.length;b.onclick=e=>{if(e.target?.closest?.('.cbZoneRouteEdit'))return;if(c)cbOpenCircuit(c);else{const made=cbNewCircuit('conventional',devices,z.id);if(made)cbOpenCircuit(made)}};return b}'''
must_sub(r"function cbZoneChoice\(z,c,compact=false\)\{.*?return b\}",zone_fn,'zone edit affordance')

manage_fn=r'''function cbRenderCircuitManagement(target,list){if(!target)return;target.textContent='';for(const c of list){const row=document.createElement('div');row.className='cbCircuitRow'+(c.complete?' done':'');row.style.setProperty('--cb-color',c.color||'#65768a');const dot=document.createElement('span');dot.className='cbDot';const label=document.createElement('div');const s=document.createElement('strong');s.textContent=c.name;const small=document.createElement('small');const editOpen=!!c.editDraft,routeOpen=!!c.editDraft?.gaps?.length;small.textContent=(c.type==='addressable'?'Addressable loop':'Zone challenge')+' · '+(c.deviceIds?.length||0)+' devices'+(cbCircuitIssue(c)?' · survey changed':editOpen?(routeOpen?' · EDITING · ROUTE OPEN':' · editing'):c.complete?' · complete':'');label.append(s,small);const open=document.createElement('button');open.textContent='Open';open.onclick=()=>cbOpenCircuit(c);const edit=document.createElement('button');edit.className='editRoute';edit.textContent='✎';edit.title='Edit cable route';edit.setAttribute('aria-label','Edit '+c.name+' route');edit.onclick=()=>{cbOpenCircuit(c);cbEnterEdit(c)};const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Remove '+c.name);remove.onclick=()=>{if(!confirm('Remove '+c.name+' and its cable route? Surveyed devices stay on the plan.'))return;push();state.circuits=cbCircuits().filter(x=>x.id!==c.id);state.asFit=null;persist();cbRenderLanding()};row.append(dot,label,open,edit,remove);target.append(row)}if(!list.length){const e=document.createElement('div');e.className='cbEmpty';e.textContent='No circuits built yet.';target.append(e)}}'''
must_sub(r"function cbRenderCircuitManagement\(target,list\)\{.*?\}\nfunction cbRenderLanding",manage_fn+'\nfunction cbRenderLanding','management edit button')

# As-Fit readiness must reject active drafts.
old="const ready=list.length>0&&list.every(c=>c.complete&&!cbCircuitIssue(c)),status=list.some(cbCircuitIssue)?'Survey devices have changed. Open the affected circuit to rebuild its route.':ready?'All created circuits are complete. Finish builds the As-Fit from the real surveyed positions.':list.length?'Complete every circuit above before finishing the As-Fit.':'Complete the circuits you create, then build the As-Fit.';"
new="const hasEdit=list.some(c=>!!c.editDraft),ready=list.length>0&&list.every(c=>c.complete&&!c.editDraft&&!cbCircuitIssue(c)),status=list.some(cbCircuitIssue)?'Survey devices have changed. Open the affected circuit to rebuild its route.':hasEdit?'Finish or repair route edits before building the As-Fit.':ready?'All created circuits are complete. Finish builds the As-Fit from the real surveyed positions.':list.length?'Complete every circuit above before finishing the As-Fit.':'Complete the circuits you create, then build the As-Fit.';"
must_replace(old,new,'asfit draft readiness')

# --- Manual editor engine: insert after cbLegSegments, before normal route target logic ---
marker="function cbLegSegments(c){const out=[];for(const leg of c?.legs||[]){const pts=leg.points||[];for(let i=1;i<pts.length;i++)out.push({a:pts[i-1],b:pts[i],color:c.color||'#2675db'})}return out}\n"
if marker not in s: raise SystemExit('cbLegSegments marker not found')
editor=r'''
function cbEditClone(v){return JSON.parse(JSON.stringify(v))}
function cbEditBoardClose(a,b,e=.00001){return !!a&&!!b&&Math.hypot(a.x-b.x,a.y-b.y)<=e}
function cbEditSimplifyBoard(points){const out=[];for(const p of points||[]){if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y))continue;const q={x:p.x,y:p.y},last=out.at(-1);if(last&&cbEditBoardClose(last,q))continue;out.push(q);while(out.length>=3){const a=out.at(-3),b=out.at(-2),c=out.at(-1),sameX=Math.abs(a.x-b.x)<1e-6&&Math.abs(b.x-c.x)<1e-6,sameY=Math.abs(a.y-b.y)<1e-6&&Math.abs(b.y-c.y)<1e-6;if(!(sameX||sameY))break;out.splice(out.length-2,1)}}return out}
function cbEditGapMatches(g,li,a,b){return g?.legIndex===li&&((cbEditBoardClose(g.a,a)&&cbEditBoardClose(g.b,b))||(cbEditBoardClose(g.a,b)&&cbEditBoardClose(g.b,a)))}
function cbEditDraft(c=cbCircuit){return c?.editDraft||null}
function cbEditVisibleSegments(c=cbCircuit){const d=c?.editDraft,out=[],legs=d?.legs||c?.legs||[],gaps=d?.gaps||[];for(let li=0;li<legs.length;li++){const pts=legs[li]?.points||[];for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];if(gaps.some(g=>cbEditGapMatches(g,li,a,b)))continue;out.push({a,b,color:c.color||'#2675db',legIndex:li,segmentIndex:i-1})}}return out}
function cbEditEnsureDraft(c=cbCircuit){if(!c)return null;if(!c.editDraft)c.editDraft={legs:cbEditClone(c.legs||[]),gaps:[],pending:null,bridges:cbEditClone(c.bridges||[]),cleanup:45};if(!Array.isArray(c.editDraft.gaps))c.editDraft.gaps=[];if(!Array.isArray(c.editDraft.bridges))c.editDraft.bridges=[];if(!Number.isFinite(c.editDraft.cleanup))c.editDraft.cleanup=45;return c.editDraft}
function cbEditSnapshot(){return cbCircuit?.editDraft?cbEditClone(cbCircuit.editDraft):null}
function cbEditPush(){if(!cbEdit?.active)return;const snap=cbEditSnapshot();if(!snap)return;cbEdit.undo.push(snap);if(cbEdit.undo.length>50)cbEdit.undo.shift();cbEdit.redo=[]}
function cbEditRestore(snap){if(!cbCircuit||!snap)return;cbCircuit.editDraft=cbEditClone(snap);cbEdit.pending=cbCircuit.editDraft.pending||null;cbEdit.stroke=null;persist();cbEditSyncUi();cbDrawBoard()}
function cbEditUndo(){if(!cbEdit?.active||!cbEdit.undo.length)return false;const now=cbEditSnapshot(),snap=cbEdit.undo.pop();if(now)cbEdit.redo.push(now);cbEditRestore(snap);return true}
function cbEditRedo(){if(!cbEdit?.active||!cbEdit.redo.length)return false;const now=cbEditSnapshot(),snap=cbEdit.redo.pop();if(now)cbEdit.undo.push(now);cbEditRestore(snap);return true}
function cbEditRouteOpen(){return !!cbCircuit?.editDraft?.gaps?.length}
function cbEditCleanupLabel(v){return v<25?'Light':v<70?'Normal':'Strong'}
function cbEditSyncUi(){const active=!!(cbEdit?.active&&cbCircuit&&cbEdit.circuitId===cbCircuit.id),bar=$('cbEditBar'),toggle=$('cbEditToggle'),status=$('cbEditStatus');if(bar)bar.hidden=!active;if(toggle)toggle.classList.toggle('active',active);$('cbBoardWrap')?.classList.toggle('editing',active);$('cbBoardWrap')?.classList.toggle('routeOpen',active&&cbEditRouteOpen());if(!active){if($('cbUndoLeg'))$('cbUndoLeg').hidden=false;if($('cbReset'))$('cbReset').hidden=false;if($('cbComplete'))$('cbComplete').hidden=false;return}const d=cbEditEnsureDraft();cbEdit.pending=d.pending||null;const open=cbEditRouteOpen(),pending=!!d.pending;if(status){status.textContent=open?'EDITING · ROUTE OPEN':pending?'EDITING · REPLACEMENT READY':'EDITING';status.classList.toggle('open',open);status.classList.toggle('ready',pending&&!open)}for(const [id,on] of [['cbEditPencil',cbEdit.mode==='pencil'],['cbEditBin',cbEdit.mode==='bin'],['cbEditBridge',!!cbEdit.bridge]])$(id)?.classList.toggle('active',on);if($('cbEditBridge'))$('cbEditBridge').setAttribute('aria-pressed',String(!!cbEdit.bridge));if($('cbEditUndo'))$('cbEditUndo').disabled=!cbEdit.undo.length;if($('cbEditRedo'))$('cbEditRedo').disabled=!cbEdit.redo.length;if($('cbEditClean'))$('cbEditClean').value=String(d.cleanup);if($('cbEditCleanValue'))$('cbEditCleanValue').textContent=cbEditCleanupLabel(d.cleanup);if($('cbUndoLeg'))$('cbUndoLeg').hidden=true;if($('cbReset'))$('cbReset').hidden=true;if($('cbComplete'))$('cbComplete').hidden=true}
function cbEnterEdit(c=cbCircuit){if(!c||!c.legs?.length){uiToast('Build some cable before editing the route','warn');return false}cbCheckpointDrag(true);cbCircuit=c;const d=cbEditEnsureDraft(c);cbEdit={active:true,circuitId:c.id,mode:'pencil',bridge:false,pending:d.pending||null,stroke:null,undo:[],redo:[]};state.asFit=null;persist();cbSyncEditUi();cbDrawBoard();return true}
function cbLeaveEditRuntime(){cbEdit=null;cbSyncEditUi();cbDrawBoard()}
function cbEditProjectToSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)return{t:0,p:{...a},d:Math.hypot(p.x-a.x,p.y-a.y)};const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l2),q={x:a.x+dx*t,y:a.y+dy*t};return{t,p:q,d:Math.hypot(p.x-q.x,p.y-q.y)}}
function cbEditAnchorAt(p,w,h){const d=cbEditEnsureDraft(),legs=d?.legs||[],gaps=d?.gaps||[],deviceHits=[];for(let li=0;li<legs.length;li++){const leg=legs[li],pts=leg.points||[];if(pts.length<2)continue;for(const [deviceId,pos,point] of [[leg.from,0,pts[0]],[leg.to,pts.length-1,pts.at(-1)]]){const q=cbBoardPx(point,w,h),dist=Math.hypot(p.x-q.x,p.y-q.y);if(dist<=30)deviceHits.push({deviceId,dist,candidate:{legIndex:li,pos,point:{...point}}})}}if(deviceHits.length){deviceHits.sort((a,b)=>a.dist-b.dist);const id=deviceHits[0].deviceId,candidates=deviceHits.filter(x=>x.deviceId===id).map(x=>x.candidate);return{kind:'device',deviceId:id,candidates,point:{...candidates[0].point}}}let best=null;for(let li=0;li<legs.length;li++){const pts=legs[li]?.points||[];for(let si=0;si<pts.length-1;si++){const a=pts[si],b=pts[si+1];if(gaps.some(g=>cbEditGapMatches(g,li,a,b)))continue;const A=cbBoardPx(a,w,h),B=cbBoardPx(b,w,h),q=cbEditProjectToSegment(p,A,B);if(q.d<=24&&(!best||q.d<best.d))best={kind:'segment',legIndex:li,segmentIndex:si,t:q.t,pos:si+q.t,point:cbPxBoard(q.p,w,h),d:q.d}}return best}
function cbEditHitSegment(p,w,h){const d=cbEditEnsureDraft(),legs=d?.legs||[],gaps=d?.gaps||[];let best=null;for(let li=0;li<legs.length;li++){const pts=legs[li]?.points||[];for(let si=0;si<pts.length-1;si++){const a=pts[si],b=pts[si+1];if(gaps.some(g=>cbEditGapMatches(g,li,a,b)))continue;const q=cbEditProjectToSegment(p,cbBoardPx(a,w,h),cbBoardPx(b,w,h));if(q.d<=25&&(!best||q.d<best.d))best={legIndex:li,segmentIndex:si,d:q.d}}}return best}
function cbEditAnchorCandidates(a){return a?.kind==='device'?(a.candidates||[]):a?[{legIndex:a.legIndex,pos:a.pos,point:a.point}]:[]}
function cbEditResolveAnchors(a,b){let best=null;for(const x of cbEditAnchorCandidates(a))for(const y of cbEditAnchorCandidates(b))if(x.legIndex===y.legIndex&&Math.abs(x.pos-y.pos)>.05){const span=Math.abs(x.pos-y.pos);if(!best||span<best.span)best={legIndex:x.legIndex,startPos:x.pos,endPos:y.pos,startPoint:{...x.point},endPoint:{...y.point},span}}return best}
function cbEditOrthogonalPush(out,q,preferH){const last=out.at(-1);if(!last){out.push({...q});return}const dx=q.x-last.x,dy=q.y-last.y;if(Math.abs(dx)<.5&&Math.abs(dy)<.5)return;if(Math.abs(dx)>.5&&Math.abs(dy)>.5)out.push(preferH?{x:q.x,y:last.y}:{x:last.x,y:q.y});out.push({...q})}
function cbEditDoglegClean(points,w,h,strength){let pts=cbPruneRouteNoise(points,w,h),grid=Math.max(8,Math.min(cbRouteCellPx(w,h).x,cbRouteCellPx(w,h).y)),limit=grid*(.55+Math.max(0,strength-35)/65*1.55),guard=0,changed=true;while(changed&&guard++<16){changed=false;for(let i=0;i<pts.length-3;i++){const a=pts[i],b=pts[i+1],c=pts[i+2],d=pts[i+3],ab=cbRouteAxis(a,b),bc=cbRouteAxis(b,c),cd=cbRouteAxis(c,d);if(!ab||!bc||!cd||ab!==cd||ab===bc)continue;const middle=Math.hypot(c.x-b.x,c.y-b.y);if(middle>limit)continue;const corner=ab==='h'?{x:d.x,y:a.y}:{x:a.x,y:d.y},candidate=cbSimplify([...pts.slice(0,i+1),corner,d,...pts.slice(i+4)]);if(candidate.every((q,j)=>j===0||cbRouteAxis(candidate[j-1],q))){pts=candidate;changed=true;break}}}return cbSimplify(pts)}
function cbEditCleanStroke(raw,start,end,w,h,strength=45){strength=clamp(Number(strength)||0,0,100);const grid=Math.max(8,Math.min(cbRouteCellPx(w,h).x,cbRouteCellPx(w,h).y)),minStep=grid*(.16+strength/100*.42),chosen=[{...start}],src=(raw||[]).filter(p=>Number.isFinite(p?.x)&&Number.isFinite(p?.y));let last={...start};for(let i=1;i<src.length-1;i++){const p=src[i];if(Math.hypot(p.x-last.x,p.y-last.y)<minStep)continue;const q=cbSnapPx(p,w,h);chosen.push(q);last=q}chosen.push({...end});let out=[{...start}],axis=null;for(let i=1;i<chosen.length;i++){const q=chosen[i],prev=out.at(-1),dx=q.x-prev.x,dy=q.y-prev.y,preferH=axis?axis==='h':Math.abs(dx)>=Math.abs(dy);const before=out.length;cbEditOrthogonalPush(out,q,preferH);if(out.length>before){const a=out.at(-2),b=out.at(-1);axis=cbRouteAxis(a,b)||axis}}out=cbSimplify(out);if(strength>=25)out=cbEditDoglegClean(out,w,h,strength);out[0]={...start};out[out.length-1]={...end};return cbSimplify(out)}
function cbEditStartStroke(anchor,p,w,h){if(!cbEdit?.active||cbEdit.mode!=='pencil'||!anchor)return false;cbEdit.stroke={start:cbEditClone(anchor),raw:[{...p}],w,h};cbDrawBoard();return true}
function cbEditMoveStroke(p,w,h){if(!cbEdit?.stroke)return;const last=cbEdit.stroke.raw.at(-1);if(!last||Math.hypot(last.x-p.x,last.y-p.y)>=1.25)cbEdit.stroke.raw.push({...p});cbDrawBoard()}
function cbEditSegmentIntersection(a,b,c,d){const ah=Math.abs(a.y-b.y)<1.25,av=Math.abs(a.x-b.x)<1.25,ch=Math.abs(c.y-d.y)<1.25,cv=Math.abs(c.x-d.x)<1.25;if(ah&&ch){if(Math.abs(a.y-c.y)>2)return null;const lo=Math.max(Math.min(a.x,b.x),Math.min(c.x,d.x)),hi=Math.min(Math.max(a.x,b.x),Math.max(c.x,d.x));return hi-lo>4?{type:'overlap',point:{x:(lo+hi)/2,y:a.y}}:null}if(av&&cv){if(Math.abs(a.x-c.x)>2)return null;const lo=Math.max(Math.min(a.y,b.y),Math.min(c.y,d.y)),hi=Math.min(Math.max(a.y,b.y),Math.max(c.y,d.y));return hi-lo>4?{type:'overlap',point:{x:a.x,y:(lo+hi)/2}}:null}if(!(ah&&cv||av&&ch))return null;const hA=ah?a:c,hB=ah?b:d,vA=ah?c:a,vB=ah?d:b,p={x:vA.x,y:hA.y};const e=2;if(p.x<=Math.min(hA.x,hB.x)+e||p.x>=Math.max(hA.x,hB.x)-e||p.y<=Math.min(vA.y,vB.y)+e||p.y>=Math.max(vA.y,vB.y)-e)return null;return{type:'cross',point:p}}
function cbEditCircuitPointPx(c,p,w,h){if(c?.id===cbCircuit?.id)return cbBoardPx(p,w,h);const plan=cbBoardToPlan(p,c.bounds||{x1:0,y1:0,x2:1,y2:1}),board=cbPlanToBoard(plan,cbCircuit?.bounds||{x1:0,y1:0,x2:1,y2:1});return cbBoardPx(board,w,h)}
function cbEditCrossingsForPath(path,legIndex,startPos,endPos,w,h){const segs=[];for(let i=1;i<path.length;i++)segs.push({a:path[i-1],b:path[i],axis:cbRouteAxis(path[i-1],path[i])});const obstacles=[],d=cbEditEnsureDraft(),lo=Math.min(startPos,endPos),hi=Math.max(startPos,endPos);for(let li=0;li<d.legs.length;li++){const pts=d.legs[li]?.points||[];for(let si=0;si<pts.length-1;si++){if(li===legIndex&&si+.5>=lo&&si+.5<=hi)continue;if(d.gaps.some(g=>cbEditGapMatches(g,li,pts[si],pts[si+1])))continue;obstacles.push({a:cbBoardPx(pts[si],w,h),b:cbBoardPx(pts[si+1],w,h),own:true})}}for(const c of cbCircuits()){if(c.id===cbCircuit.id)continue;const legs=c.editDraft?.legs||c.legs||[];for(const leg of legs){const pts=leg.points||[];for(let i=1;i<pts.length;i++)obstacles.push({a:cbEditCircuitPointPx(c,pts[i-1],w,h),b:cbEditCircuitPointPx(c,pts[i],w,h),own:false})}}const crossings=[],overlaps=[];for(const s of segs)for(const o of obstacles){const hit=cbEditSegmentIntersection(s.a,s.b,o.a,o.b);if(!hit)continue;(hit.type==='overlap'?overlaps:crossings).push({...hit,axis:s.axis})}for(let i=0;i<segs.length;i++)for(let j=0;j<i-1;j++){const hit=cbEditSegmentIntersection(segs[i].a,segs[i].b,segs[j].a,segs[j].b);if(hit)(hit.type==='overlap'?overlaps:crossings).push({...hit,axis:segs[i].axis})}return{crossings,overlaps}}
function cbEditFinishStroke(endAnchor,w,h){const stroke=cbEdit?.stroke;if(!stroke||!endAnchor){if(cbEdit)cbEdit.stroke=null;cbDrawBoard();return false}const pair=cbEditResolveAnchors(stroke.start,endAnchor);if(!pair){cbEdit.stroke=null;uiToast('Finish on the same detector-to-detector cable leg','warn');cbDrawBoard();return false}const startPx=cbBoardPx(pair.startPoint,w,h),endPx=cbBoardPx(pair.endPoint,w,h),d=cbEditEnsureDraft(),path=cbEditCleanStroke(stroke.raw,startPx,endPx,w,h,d.cleanup),conflict=cbEditCrossingsForPath(path,pair.legIndex,pair.startPos,pair.endPos,w,h);cbEdit.stroke=null;if(conflict.overlaps.length){uiToast('Replacement overlaps existing cable · choose a separate lane','warn');cbDrawBoard();return false}if(conflict.crossings.length&&!cbEdit.bridge){uiToast('Bridge OFF · route around existing cable or turn Bridge on','warn');cbDrawBoard();return false}cbEditPush();const bridges=cbEdit.bridge?conflict.crossings.map(h=>({point:cbPxBoard(h.point,w,h),axis:h.axis||'h'})):[];const pending={legIndex:pair.legIndex,startPos:pair.startPos,endPos:pair.endPos,startPoint:pair.startPoint,endPoint:pair.endPoint,points:path.map(p=>cbPxBoard(p,w,h)),bridges};d.pending=pending;cbEdit.pending=pending;persist();cbEditSyncUi();cbDrawBoard();return true}
function cbEditPointAtPos(pts,pos){if(!pts.length)return null;if(pos<=0)return{...pts[0]};if(pos>=pts.length-1)return{...pts.at(-1)};const i=Math.floor(pos),t=pos-i,a=pts[i],b=pts[i+1];return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}
function cbEditSplicePending(){const d=cbEditEnsureDraft(),p=d?.pending;if(!p)return false;const leg=d.legs[p.legIndex],pts=leg?.points||[];if(pts.length<2)return false;const lo=Math.min(p.startPos,p.endPos),hi=Math.max(p.startPos,p.endPos),lowPoint=cbEditPointAtPos(pts,lo),highPoint=cbEditPointAtPos(pts,hi);let replacement=cbEditClone(p.points||[]);if(p.startPos>p.endPos)replacement.reverse();replacement[0]=lowPoint;replacement[replacement.length-1]=highPoint;const loFloor=Math.floor(lo),hiFloor=Math.floor(hi),prefix=pts.slice(0,loFloor+1),suffix=Number.isInteger(hi)?pts.slice(hiFloor+1):pts.slice(hiFloor+1),combined=[...prefix];if(!cbEditBoardClose(combined.at(-1),lowPoint))combined.push(lowPoint);for(const q of replacement.slice(1,-1))if(!cbEditBoardClose(combined.at(-1),q))combined.push(q);if(!cbEditBoardClose(combined.at(-1),highPoint))combined.push(highPoint);for(const q of suffix)if(!cbEditBoardClose(combined.at(-1),q))combined.push(q);leg.points=cbEditSimplifyBoard(combined);d.gaps=d.gaps.filter(g=>!(g.legIndex===p.legIndex&&g.segmentIndex>=Math.floor(lo)&&g.segmentIndex<=Math.floor(hi)));for(const b of p.bridges||[])d.bridges.push({legIndex:p.legIndex,point:b.point,axis:b.axis});d.pending=null;cbEdit.pending=null;return true}
function cbEditDeleteSegment(hit){if(!cbEdit?.active||!hit)return false;const d=cbEditEnsureDraft(),leg=d.legs[hit.legIndex],pts=leg?.points||[],si=hit.segmentIndex;if(si<0||si>=pts.length-1)return false;const pending=d.pending,mid=si+.5;if(pending&&pending.legIndex===hit.legIndex&&mid>=Math.min(pending.startPos,pending.endPos)&&mid<=Math.max(pending.startPos,pending.endPos)){cbEditPush();const ok=cbEditSplicePending();persist();cbEditSyncUi();cbDrawBoard();return ok}if(d.gaps.some(g=>cbEditGapMatches(g,hit.legIndex,pts[si],pts[si+1])))return false;cbEditPush();d.gaps.push({legIndex:hit.legIndex,segmentIndex:si,a:{...pts[si]},b:{...pts[si+1]}});d.bridges=d.bridges.filter(b=>!(b.legIndex===hit.legIndex));persist();cbEditSyncUi();cbDrawBoard();return true}
function cbEditValidateDraft(){const d=cbEditEnsureDraft();if(!d)return{ok:false,message:'No edit draft'};if(d.pending)return{ok:false,message:'Delete the old cable section to apply the staged replacement'};if(d.gaps.length)return{ok:false,message:'Route is open · reconnect the deleted cable section'};if(d.legs.length!==(cbCircuit.legs||[]).length)return{ok:false,message:'Circuit leg count changed unexpectedly'};for(let li=0;li<d.legs.length;li++){const leg=d.legs[li],pts=leg.points||[];if(pts.length<2)return{ok:false,message:'A cable leg has no route'};if(leg.from!==cbCircuit.legs[li]?.from||leg.to!==cbCircuit.legs[li]?.to)return{ok:false,message:'Device order changed unexpectedly'};for(let i=0;i<pts.length;i++){const p=pts[i];if(!Number.isFinite(p.x)||!Number.isFinite(p.y))return{ok:false,message:'Cable contains an invalid coordinate'};if(i&&Math.hypot(p.x-pts[i-1].x,p.y-pts[i-1].y)<1e-7)return{ok:false,message:'Cable contains a zero-length segment'};if(i&&Math.abs(p.x-pts[i-1].x)>1e-5&&Math.abs(p.y-pts[i-1].y)>1e-5)return{ok:false,message:'Cable contains a non-orthogonal segment'}}}if(!cbSequenceReady(cbCircuit,cbCircuit.sequence))return{ok:false,message:'Circuit device sequence is not complete'};return{ok:true}}
function cbEditDone(){if(!cbEdit?.active)return false;const check=cbEditValidateDraft();if(!check.ok){uiToast(check.message,'warn');cbEditSyncUi();return false}const d=cbEditEnsureDraft();push();cbCircuit.legs=cbEditClone(d.legs);cbCircuit.bridges=cbEditClone(d.bridges||[]);delete cbCircuit.editDraft;cbCircuit.complete=cbSequenceReady(cbCircuit,cbCircuit.sequence);cbCircuit.updatedAt=Date.now();state.asFit=null;persist();cbEdit=null;cbSyncEditUi();cbUpdateGame();cbRenderLanding();uiToast('Route edit validated and saved','success');return true}
function cbEditSetMode(mode){if(!cbEdit?.active)return;cbEdit.mode=mode;cbEdit.stroke=null;cbSyncEditUi();cbDrawBoard()}
function cbEditPointerDown(e,p,w,h){if(!cbEdit?.active)return false;if(cbEdit.mode==='pencil'){const a=cbEditAnchorAt(p,w,h);if(!a){$('cbBoardHint').textContent='Pencil: start directly on existing cable or a device';return true}cbEditStartStroke(a,p,w,h);cbEdit.stroke.pointerId=e.pointerId;$('cbBoardHint').textContent='Keep drawing · finish on existing cable or a device';return true}cbEdit.tap={pointerId:e.pointerId,start:{...p}};return true}
function cbEditPointerMove(e,samples,w,h){if(!cbEdit?.active)return false;if(cbEdit.mode==='pencil'&&cbEdit.stroke?.pointerId===e.pointerId)for(const p of samples)cbEditMoveStroke(p,w,h);return true}
function cbEditPointerUp(e,p,w,h){if(!cbEdit?.active)return false;if(cbEdit.mode==='pencil'&&cbEdit.stroke?.pointerId===e.pointerId){const end=cbEditAnchorAt(p,w,h);cbEditFinishStroke(end,w,h);return true}if(cbEdit.mode==='bin'&&cbEdit.tap?.pointerId===e.pointerId){const moved=Math.hypot(p.x-cbEdit.tap.start.x,p.y-cbEdit.tap.start.y);cbEdit.tap=null;if(moved>12)return true;const hit=cbEditHitSegment(p,w,h);if(!hit){uiToast('Tap directly on the cable segment to delete','warn');return true}cbEditDeleteSegment(hit);return true}return true}
function cbEditVisibleBridgeList(c=cbCircuit){return c?.editDraft?.bridges||c?.bridges||[]}
function cbPaintBridgeMark(x,p,axis,color,width=5,scale=1){const r=Math.max(5,7*scale);x.save();x.translate(p.x,p.y);if(axis==='v')x.rotate(Math.PI/2);x.lineCap='round';x.lineWidth=width+5;x.strokeStyle='#fff';x.beginPath();x.arc(0,0,r,Math.PI,0);x.stroke();x.lineWidth=width;x.strokeStyle=color;x.beginPath();x.arc(0,0,r,Math.PI,0);x.stroke();x.restore()}
function cbDrawCircuitBridges(x,c,w,h,mapPoint=null){const list=c?.id===cbCircuit?.id?cbEditVisibleBridgeList(c):(c?.bridges||[]),map=mapPoint||(p=>cbBoardPx(p,w,h));for(const b of list){const p=map(b.point);if(p)cbPaintBridgeMark(x,p,b.axis||'h',c.color||'#2675db',5,Math.sqrt(Math.max(1,cbView.scale)))}}
function cbDrawEditorOverlay(x,w,h,color){if(!cbEdit?.active)return;const d=cbEditEnsureDraft(),pending=d.pending;if(pending?.points?.length>1){x.save();x.strokeStyle='#fff';x.lineWidth=9;x.lineCap='round';x.lineJoin='round';x.setLineDash([11,6]);x.beginPath();pending.points.forEach((p,i)=>{const q=cbBoardPx(p,w,h);i?x.lineTo(q.x,q.y):x.moveTo(q.x,q.y)});x.stroke();x.strokeStyle=color;x.lineWidth=5;x.beginPath();pending.points.forEach((p,i)=>{const q=cbBoardPx(p,w,h);i?x.lineTo(q.x,q.y):x.moveTo(q.x,q.y)});x.stroke();x.restore()}if(cbEdit.stroke?.raw?.length>1){x.save();x.strokeStyle=color;x.lineWidth=3;x.globalAlpha=.62;x.lineCap='round';x.lineJoin='round';x.setLineDash([5,4]);x.beginPath();cbEdit.stroke.raw.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();x.restore()}}
'''
s=s.replace(marker,marker+editor,1)

# --- Render draft route + overlays/bridges ---
old="const committed=cbLegSegments({...cbCircuit,color:routeColor}),preview=cbDrag?.previewLegs?.length?cbLegSegments({legs:cbDrag.previewLegs,color:routeColor}):[];cbDrawBundled(x,[...committed,...preview],p=>cbBoardPx(p,w,h),5,Math.max(8,Math.min(12,8*Math.sqrt(Math.max(1,cbView.scale)))));if(cbDrag?.points?.length>1){"
new="const committed=cbEdit?.active&&cbEdit.circuitId===cbCircuit.id?cbEditVisibleSegments(cbCircuit):cbLegSegments({...cbCircuit,color:routeColor}),preview=cbDrag?.previewLegs?.length?cbLegSegments({legs:cbDrag.previewLegs,color:routeColor}):[];cbDrawBundled(x,[...committed,...preview],p=>cbBoardPx(p,w,h),5,Math.max(8,Math.min(12,8*Math.sqrt(Math.max(1,cbView.scale)))));cbDrawCircuitBridges(x,cbCircuit,w,h);cbDrawEditorOverlay(x,w,h,routeColor);if(cbDrag?.points?.length>1){"
must_replace(old,new,'paint edit draft')

# History circuits in conventional challenge also retain bridge marks.
old="for(const old of history){const oldSegs=cbLegSegments(old);cbDrawBundled(x,oldSegs,p=>cbChallengeMapPointPx(old,p,w,h),4.5,6.5)}"
new="for(const old of history){const oldSegs=cbLegSegments(old);cbDrawBundled(x,oldSegs,p=>cbChallengeMapPointPx(old,p,w,h),4.5,6.5);cbDrawCircuitBridges(x,old,w,h,p=>cbChallengeMapPointPx(old,p,w,h))}"
must_replace(old,new,'history bridge render')

# --- Pointer integration ---
old="if(cbGestureLock)return;if(cbScreen==='select'){"
new="if(cbGestureLock)return;if(cbEdit?.active&&cbScreen==='game'){cbEditPointerDown(e,p,w,h);return}if(cbScreen==='select'){"
must_replace(old,new,'editor pointer down')
old="if(cbPinch){cbUpdatePinch(w,h);return}if(cbGestureLock||cbDrag?.pointerId!==e.pointerId)return;cbProcessSamples(samples,w,h);cbDrawBoard()"
new="if(cbPinch){cbUpdatePinch(w,h);return}if(cbEdit?.active&&cbScreen==='game'){if(cbGestureLock)return;cbEditPointerMove(e,samples,w,h);return}if(cbGestureLock||cbDrag?.pointerId!==e.pointerId)return;cbProcessSamples(samples,w,h);cbDrawBoard()"
must_replace(old,new,'editor pointer move')
old="if(locked){if(cbPinch?.ids.includes(e.pointerId))cbPinch=null;if(!cbPointers.size)cbGestureLock=false;return}if(cbDrag?.pointerId!==e.pointerId)return;if(cbScreen==='select'){"
new="if(locked){if(cbPinch?.ids.includes(e.pointerId))cbPinch=null;if(!cbPointers.size)cbGestureLock=false;return}if(cbEdit?.active&&cbScreen==='game'){cbEditPointerUp(e,p,r.width,r.height);return}if(cbDrag?.pointerId!==e.pointerId)return;if(cbScreen==='select'){"
must_replace(old,new,'editor pointer up')
old="function cbCanvasCancel(e){if(!cbPointers.has(e.pointerId))return;cbPointers.delete(e.pointerId);cbPinch=null;cbGestureLock=cbPointers.size>0;cbDrag=null;cbHover=null;cbUpdateGame();cbDrawBoard()}"
new="function cbCanvasCancel(e){if(!cbPointers.has(e.pointerId))return;cbPointers.delete(e.pointerId);cbPinch=null;cbGestureLock=cbPointers.size>0;if(cbEdit?.active){cbEdit.stroke=null;cbEdit.tap=null;cbDrawBoard();return}cbDrag=null;cbHover=null;cbUpdateGame();cbDrawBoard()}"
must_replace(old,new,'editor pointer cancel')

# --- Open/close circuit integration ---
old="function closeCircuitBuilder(){cbCheckpointDrag(true);cbHideCelebrate();$('circuitBuilder').hidden=true;document.querySelector('.app').inert=false;cbDrag=null;cbHover=null;saveNow();draw()}"
new="function closeCircuitBuilder(){cbCheckpointDrag(true);cbHideCelebrate();$('circuitBuilder').hidden=true;document.querySelector('.app').inert=false;cbDrag=null;cbEdit=null;cbHover=null;cbSyncEditUi();saveNow();draw()}"
must_replace(old,new,'close edit runtime')
# Append resume edit to end of cbOpenCircuit.
must_sub(r"function cbOpenCircuit\(c\)\{(.*?)cbRenderLanding\(\);cbUpdateGame\(\);cbDrawBoard\(\)\}",lambda m:"function cbOpenCircuit(c){"+m.group(1)+"cbRenderLanding();cbUpdateGame();cbDrawBoard();if(c.editDraft)cbEnterEdit(c)}",'resume edit draft')

# --- As-Fit bridge rendering and draft block ---
old="const size=Math.min(pw,ph)*.018,cableWidth=Math.max(1.05,size*.13),bundleGap=Math.max(cableWidth*1.9,size*.22),segments=cbAsFitSegments();cbDrawBundled(x,segments,map,cableWidth,bundleGap);for(const s of state.symbols||[]){"
new="const size=Math.min(pw,ph)*.018,cableWidth=Math.max(1.05,size*.13),bundleGap=Math.max(cableWidth*1.9,size*.22),segments=cbAsFitSegments();cbDrawBundled(x,segments,map,cableWidth,bundleGap);for(const circuit of cbCircuits().filter(c=>c.complete&&!c.editDraft&&!cbCircuitIssue(c)))for(const b of circuit.bridges||[]){const plan=cbBoardToPlan(b.point,circuit.bounds),p=map(plan);cbPaintBridgeMark(x,p,b.axis||'h',circuit.color||'#2675db',cableWidth,Math.max(1,uiScale*.7))}for(const s of state.symbols||[]){"
must_replace(old,new,'asfit bridge render')
old="function cbFinishAsFit(){const list=cbCircuits();if(!list.length||!list.every(c=>c.complete&&!cbCircuitIssue(c)))return;"
new="function cbFinishAsFit(){const list=cbCircuits();if(!list.length||!list.every(c=>c.complete&&!c.editDraft&&!cbCircuitIssue(c)))return;"
must_replace(old,new,'asfit edit block')

# --- Control wiring ---
old="$ ('cbZoomIn')" # unused guard
# Exact event tail replacement.
events="$('cbZoomIn').onclick=()=>cbZoomAt(1.35);$('cbZoomOut').onclick=()=>cbZoomAt(1/1.35);$('cbZoomFit').onclick=()=>cbResetView(true);"
replacement="$('cbZoomIn').onclick=()=>cbZoomAt(1.35);$('cbZoomOut').onclick=()=>cbZoomAt(1/1.35);$('cbZoomFit').onclick=()=>cbResetView(true);$('cbEditToggle').onclick=()=>{if(cbEdit?.active)return;cbEnterEdit(cbCircuit)};$('cbEditPencil').onclick=()=>cbEditSetMode('pencil');$('cbEditBin').onclick=()=>cbEditSetMode('bin');$('cbEditUndo').onclick=cbEditUndo;$('cbEditRedo').onclick=cbEditRedo;$('cbEditBridge').onclick=()=>{if(!cbEdit?.active)return;cbEdit.bridge=!cbEdit.bridge;cbEditSyncUi();uiToast('Bridge mode '+(cbEdit.bridge?'ON · crossings will be explicit':'OFF'),'success')};$('cbEditClean').oninput=e=>{if(!cbEdit?.active)return;const d=cbEditEnsureDraft();d.cleanup=Number(e.target.value);persist();cbEditSyncUi()};$('cbEditDone').onclick=cbEditDone;"
must_replace(events,replacement,'editor control wiring')
# Game home keeps draft but exits runtime.
old="$ ('cbGameHome')" # no-op
must_replace("$('cbGameHome').onclick=()=>{cbCheckpointDrag(true);cbHideCelebrate();cbCircuit=null;cbShow('home')};","$('cbGameHome').onclick=()=>{cbCheckpointDrag(true);cbHideCelebrate();cbEdit=null;cbSyncEditUi();cbCircuit=null;cbShow('home')};",'game home edit runtime')

# Version-generation marker for searchability.
marker='// v0.58 Project Pineapple: a bounded virtual pointer absorbs sparse-hit overshoot, then catches back up to raw touch.'
if marker not in s: raise SystemExit('v0.58 routing marker missing')
s=s.replace(marker,marker+'\n// v0.58 Project Pineapple editor: draft-first local route surgery, explicit gaps, cleanup and bridge metadata.',1)

SRC.write_text(s,encoding='utf-8')
for rel in ['Zone-Sketch-by-Will.html','ZoneSketch.html','app/src/main/assets/index.html']:
    shutil.copyfile(SRC,ROOT/rel)
print('Applied Project Pineapple v0.58 manual route editor core to all app copies')
