from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]; INDEX=ROOT/'index.html'
def fn(t,n,nxt,b):
 p=re.compile(rf"function {re.escape(n)}\([\s\S]*?(?=\nfunction {re.escape(nxt)}\()" ); t2,c=p.subn(b.rstrip(),t,count=1)
 if c!=1: raise SystemExit(f'function patch {n}: {c}')
 return t2
def rep(t,a,b,label):
 if a not in t: raise SystemExit('missing '+label)
 return t.replace(a,b,1)
t=INDEX.read_text()
for a,b in [('<title>Zone Sketch by Will Flood v0.56 —','<title>Zone Sketch by Will Flood v0.57 —'),('ZONE SKETCH · v0.56</div>','ZONE SKETCH · v0.57</div>'),('BETA v0.56</small>','BETA v0.57</small>'),('<b>v0.56</b> · DESIGNED','<b>v0.57</b> · DESIGNED')]: t=t.replace(a,b)
a="const CB_ROUTE_GRID=24,CB_ROUTE_TURN_CELLS=.72,CB_ROUTE_ARM_CELLS=.28,CB_ROUTE_SAMPLE_CELLS=.30,CB_INSET=.045,CB_SPAN=.91,CB_DEVICE_R=11,CB_PANEL_R=16,CB_PAIR_GAP=9,CB_PAIR_RANGE=24,CB_COLORS=['#e33a3a','#2675db','#20a36b','#dc9c16','#9957c5','#e26929','#1d9baa','#d04a88'];"
b="const CB_ROUTE_GRID=24,CB_ROUTE_TURN_CELLS=.72,CB_ROUTE_ARM_CELLS=.28,CB_ROUTE_SAMPLE_CELLS=.30,CB_ROUTE_COMMIT_CELLS=.92,CB_ROUTE_INTENT_CELLS=.45,CB_ROUTE_REVERSAL_CELLS=.90,CB_DEVICE_CORRIDOR=30,CB_INSET=.045,CB_SPAN=.91,CB_DEVICE_R=11,CB_PANEL_R=16,CB_PAIR_GAP=9,CB_PAIR_RANGE=24,CB_COLORS=['#e33a3a','#2675db','#20a36b','#dc9c16','#9957c5','#e26929','#1d9baa','#d04a88'];"
t=rep(t,a,b,'routing constants')
t=fn(t,'cbCanvasAbort','cbNodesAlong',r'''function cbCanvasAbort(){cbDrag=null;cbHover=null;cbPointers.clear();cbPinch=null;cbGestureLock=false;cbClearReward();cbUpdateGame();cbDrawBoard()}
// v0.57 Smart Route — raw pointer input, device-hit corridor and rendered cable geometry are independent layers.
function cbRoutingState(){if(cbReturnPhase())return'returning';return cbDrag?.state||'waiting-to-start'}
function cbSetRoutingState(next){if(cbDrag)cbDrag.state=next;return next}
function cbRecordRawPointer(p){if(!cbDrag||!p)return;const raw=cbDrag.rawInput||(cbDrag.rawInput=[]),last=raw.at(-1);if(!last||Math.hypot(last.x-p.x,last.y-p.y)>.35){raw.push({x:p.x,y:p.y});if(raw.length>180)raw.splice(0,raw.length-180)}}
function cbRouteIntentPoint(p,w,h,force=false){if(!cbDrag||!p)return p;const cell=cbRouteCellPx(w,h),gate=Math.max(5,Math.min(cell.x,cell.y)*CB_ROUTE_INTENT_CELLS),prev=cbDrag.intentInput||cbDrag.routeInput||cbDrag.points?.at(-1)||p,d=Math.hypot(p.x-prev.x,p.y-prev.y);if(!force&&d<gate)return null;cbDrag.intentInput={x:p.x,y:p.y};return p}''')
t=fn(t,'cbNodesAlong','cbProcessPointer',r'''function cbNodesAlong(a,b,w,h,selection=false){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy,ids=selection?cbSurveyDevices().map(d=>d.id):[cbCircuit?.panelId,...(cbCircuit?.deviceIds||[])],hits=[],corridor=selection?30:CB_DEVICE_CORRIDOR;for(const id of ids){const p=cbNodePx(id,w,h);if(!p)continue;const q=l2?clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l2):0,d=Math.hypot(a.x+q*dx-p.x,a.y+q*dy-p.y);if(d<=corridor)hits.push({id,t:q,p,d})}return hits.sort((a,b)=>a.t-b.t)}''')
t=fn(t,'cbProcessPointer','cbClearReward',r'''function cbProcessPointer(p,w,h){if(!cbDrag)return;const prev=cbDrag.lastPointer||p;cbRecordRawPointer(p);if(cbDrag.select){for(const hit of cbNodesAlong(prev,p,w,h,true))cbSelection.add(hit.id);cbDrag.lastPointer=p;cbUpdateGame();return}let captured=false;for(const hit of cbNodesAlong(prev,p,w,h)){if(!cbDrag||cbCircuit?.complete)break;if(cbValidTarget(hit.id)){cbSetRoutingState('approaching-device');if(cbAppendDrag(hit.p,w,h)===false)break;if(cbCaptureDragTarget(hit.id,w,h))captured=true}}if(cbDrag?.points){if(!captured){const intent=cbReturnPhase()?p:cbRouteIntentPoint(p,w,h);if(intent)cbAppendDrag(intent,w,h)}cbDrag.lastPointer=p;cbHover=cbDrag.targets.at(-1)||null}}''')
t=fn(t,'cbCollinear','cbSimplify',r'''function cbCollinear(a,b,c){return(Math.abs(a.x-b.x)<.5&&Math.abs(b.x-c.x)<.5)||(Math.abs(a.y-b.y)<.5&&Math.abs(b.y-c.y)<.5)}''')
t=fn(t,'cbSimplify','cbPointClose',r'''function cbSimplify(points){const out=[];for(const p of points){const last=out.at(-1);if(last&&Math.hypot(last.x-p.x,last.y-p.y)<1)continue;out.push(p);while(out.length>=3&&cbCollinear(out.at(-3),out.at(-2),out.at(-1)))out.splice(out.length-2,1)}return out}''')
t=fn(t,'cbMarkBlocked','cbPairSegmentsPx',r'''function cbMarkBlocked(){if(!cbDrag)return;cbDrag.blocked=true;cbDrag.state='blocked';const now=Date.now();if(!cbMarkBlocked.last||now-cbMarkBlocked.last>320){cbMarkBlocked.last=now;if(uiHaptics)try{navigator.vibrate?.(18)}catch(e){}}}''')
t=rep(t,"function cbAppendReturnDrag(p,w,h){if(!cbDrag)return false;","function cbAppendReturnDrag(p,w,h){if(!cbDrag)return false;cbDrag.state='returning';",'return state')
t=fn(t,'cbRouteSnapshot','cbRouteRestore',r'''function cbRouteSnapshot(){return{points:(cbDrag?.points||[]).map(p=>({...p})),routeAxis:cbDrag?.routeAxis||null,routeDir:cbDrag?.routeDir||0,turnAnchor:cbDrag?.turnAnchor?{...cbDrag.turnAnchor}:null,pendingTurnDir:cbDrag?.pendingTurnDir||0,pendingTurnSamples:cbDrag?.pendingTurnSamples||0,state:cbDrag?.state||'routing',pairSide:cbDrag?.pairSide??null,pairSnap:!!cbDrag?.pairSnap,pairAxis:cbDrag?.pairAxis||null,pairLine:Number.isFinite(cbDrag?.pairLine)?cbDrag.pairLine:null,routeInput:cbDrag?.routeInput?{...cbDrag.routeInput}:null,intentInput:cbDrag?.intentInput?{...cbDrag.intentInput}:null}}''')
t=fn(t,'cbRouteRestore','cbPairSnapPx',r'''function cbRouteRestore(s){if(!cbDrag||!s)return;cbDrag.points=s.points.map(p=>({...p}));cbDrag.routeAxis=s.routeAxis;cbDrag.routeDir=s.routeDir||0;cbDrag.turnAnchor=s.turnAnchor?{...s.turnAnchor}:null;cbDrag.pendingTurnDir=s.pendingTurnDir||0;cbDrag.pendingTurnSamples=s.pendingTurnSamples||0;cbDrag.state=s.state||'routing';cbDrag.pairSide=s.pairSide;cbDrag.pairSnap=s.pairSnap;cbDrag.pairAxis=s.pairAxis;cbDrag.pairLine=s.pairLine;cbDrag.routeInput=s.routeInput?{...s.routeInput}:null;cbDrag.intentInput=s.intentInput?{...s.intentInput}:null}''')
t=fn(t,'cbRouteGridStep','cbAppendDrag',r'''function cbRouteGridStep(q,w,h,intent=q){
 if(!cbDrag?.points?.length)return;const pts=cbDrag.points,cell=cbRouteCellPx(w,h);let axis=cbDrag.routeAxis||null,last=pts.at(-1);const pairAxis=cbDrag.pairSnap?cbDrag.pairAxis:null,pairLine=cbDrag.pairSnap?cbDrag.pairLine:null,paired=!!pairAxis&&Number.isFinite(pairLine);
 if(!axis){const dx=q.x-last.x,dy=q.y-last.y,nx=Math.abs(dx)/cell.x,ny=Math.abs(dy)/cell.y;if(Math.max(nx,ny)<.28)return;axis=paired?pairAxis:(nx>=ny?'h':'v');cbDrag.routeAxis=axis;cbDrag.routeDir=Math.sign(axis==='h'?dx:dy)||cbDrag.routeDir||1;cbDrag.turnAnchor=null;cbDrag.pendingTurnDir=0;cbDrag.pendingTurnSamples=0;cbDrag.state='routing';if(paired&&axis===pairAxis){if(axis==='h'){if(Math.abs(last.y-pairLine)>.5)pts.push({x:last.x,y:pairLine});pts.push({x:q.x,y:pairLine})}else{if(Math.abs(last.x-pairLine)>.5)pts.push({x:pairLine,y:last.y});pts.push({x:pairLine,y:q.y})}}else pts.push(axis==='h'?{x:q.x,y:last.y}:{x:last.x,y:q.y});cbDrag.points=cbSimplify(pts);return}
 if(paired&&axis===pairAxis){cbDrag.turnAnchor=null;cbDrag.pendingTurnDir=0;cbDrag.pendingTurnSamples=0;cbDrag.state='routing';const delta=axis==='h'?q.x-last.x:q.y-last.y;if(Math.abs(delta)>1)cbDrag.routeDir=Math.sign(delta);if(axis==='h'){if(Math.abs(last.y-pairLine)>.5){pts.push({x:last.x,y:pairLine});last=pts.at(-1)}last.x=q.x;last.y=pairLine}else{if(Math.abs(last.x-pairLine)>.5){pts.push({x:pairLine,y:last.y});last=pts.at(-1)}last.x=pairLine;last.y=q.y}cbDrag.points=cbSimplify(pts);return}
 const raw=intent||q,perpCell=axis==='h'?cell.y:cell.x,alongCell=axis==='h'?cell.x:cell.y,signedPerp=axis==='h'?raw.y-last.y:raw.x-last.x,perp=Math.abs(signedPerp),arm=Math.max(8,perpCell*CB_ROUTE_ARM_CELLS),turn=Math.max(16,perpCell*CB_ROUTE_TURN_CELLS),cc=typeof CB_ROUTE_COMMIT_CELLS==='number'?CB_ROUTE_COMMIT_CELLS:.92,commit=Math.max(22,perpCell*cc),rc=typeof CB_ROUTE_REVERSAL_CELLS==='number'?CB_ROUTE_REVERSAL_CELLS:.90,reversal=Math.max(14,alongCell*rc);
 if(perp<arm){cbDrag.turnAnchor=null;cbDrag.pendingTurnDir=0;cbDrag.pendingTurnSamples=0;cbDrag.state='routing';const candidate=axis==='h'?q.x:q.y,current=axis==='h'?last.x:last.y,delta=candidate-current,dir=Math.sign(delta),prior=cbDrag.routeDir||dir;if(dir&&prior&&dir!==prior&&Math.abs(delta)<reversal){}else if(dir){if(dir!==prior)cbDrag.routeDir=dir;if(axis==='h')last.x=q.x;else last.y=q.y}}
 else{const td=Math.sign(signedPerp)||cbDrag.pendingTurnDir||1;if(!cbDrag.turnAnchor||(cbDrag.pendingTurnDir&&td!==cbDrag.pendingTurnDir)){cbDrag.turnAnchor={x:last.x,y:last.y};cbDrag.pendingTurnDir=td;cbDrag.pendingTurnSamples=1}else cbDrag.pendingTurnSamples=(cbDrag.pendingTurnSamples||0)+1;const a=cbDrag.turnAnchor;last.x=a.x;last.y=a.y;const required=(cbDrag.pendingTurnSamples||0)>=2?turn:commit;if(perp>=required){const next=axis==='h'?{x:a.x,y:q.y}:{x:q.x,y:a.y};if(Math.hypot(next.x-a.x,next.y-a.y)>=1)pts.push(next);cbDrag.routeAxis=axis==='h'?'v':'h';cbDrag.routeDir=Math.sign(cbDrag.routeAxis==='h'?next.x-a.x:next.y-a.y)||td;cbDrag.turnAnchor=null;cbDrag.pendingTurnDir=0;cbDrag.pendingTurnSamples=0;cbDrag.state='corner-committed'}else cbDrag.state='corner-pending'}cbDrag.points=cbSimplify(pts)
}''')
t=fn(t,'cbAppendDrag','cbCaptureDragTarget',r'''function cbAppendDrag(p,w,h){if(!cbDrag)return false;if(cbReturnPhase())return cbAppendReturnDrag(p,w,h);if(cbDrag.state==='device-captured')cbDrag.state='routing';const cell=cbRouteCellPx(w,h),sample=Math.max(4,Math.min(cell.x,cell.y)*CB_ROUTE_SAMPLE_CELLS),start=cbDrag.routeInput||cbDrag.points.at(-1)||p,dist=Math.hypot(p.x-start.x,p.y-start.y),steps=Math.max(1,Math.min(64,Math.ceil(dist/sample)));for(let i=1;i<=steps;i++){const raw={x:start.x+(p.x-start.x)*i/steps,y:start.y+(p.y-start.y)*i/steps},before=cbRouteSnapshot();let q=cbSnapPx(raw,w,h),last=cbDrag.points.at(-1);if(!last)return false;q=cbPairSnapPx(q,last,w,h,raw);cbRouteGridStep(q,w,h,raw);if(cbChallengePointsBlocked(cbDrag.points,w,h)){cbRouteRestore(before);cbDrag.routeInput=raw;cbMarkBlocked();return false}cbDrag.routeInput=raw}cbDrag.blocked=false;return true}''')
t=fn(t,'cbCaptureDragTarget','cbCommitDrag',r'''function cbCaptureDragTarget(target,w,h){if(!cbDrag?.points?.length||!cbValidTarget(target))return false;const returning=target===cbCircuit?.panelId&&cbReturnPhase(),end=cbNodePx(target,w,h),pts=returning?cbReturnGuidePx(w,h):cbDrag.points.slice();if(!end)return false;const last=pts.at(-1),dx=end.x-last.x,dy=end.y-last.y;if(Math.abs(dx)>1&&Math.abs(dy)>1){const prev=pts.at(-2),horizontal=prev?Math.abs(last.y-prev.y)<Math.abs(last.x-prev.x):Math.abs(dx)>=Math.abs(dy);pts.push(horizontal?{x:end.x,y:last.y}:{x:last.x,y:end.y})}pts.push(end);const clean=cbSimplify(pts);if(cbChallengePointsBlocked(clean,w,h)){cbMarkBlocked();return false}cbDrag.blocked=false;cbDrag.previewLegs.push({from:cbDrag.from,to:target,points:clean.map(p=>cbPxBoard(p,w,h))});cbDrag.targets.push(target);cbDrag.from=target;cbDrag.points=[end];cbDrag.routeAxis=null;cbDrag.routeDir=0;cbDrag.turnAnchor=null;cbDrag.pendingTurnDir=0;cbDrag.pendingTurnSamples=0;cbDrag.routeInput=end;cbDrag.intentInput=end;cbDrag.pairSnap=false;cbDrag.pairAxis=null;cbDrag.pairLine=null;cbDrag.state='device-captured';cbHover=target;if(target!==cbCircuit.panelId){const q=cbGameCounts();cbPlayProgressBell(q.done,q.total);cbPulseCounter();cbMilestone(q)}cbUpdateGame();const ready=cbSequenceReady(cbCircuit,[...cbCircuit.sequence,...cbDrag.targets]);if(ready){cbCommitDrag();cbAutoCompleteCircuit();return true}return true}''')
t=fn(t,'cbCanvasDown','cbCanvasMove',r'''function cbCanvasDown(e){if(e.button!==0||!['select','game'].includes(cbScreen)||!$('cbCelebrate').hidden)return;cbEnsureAudio();const c=$('cbCanvas'),r=c.getBoundingClientRect(),w=r.width,h=r.height,p=cbPointInCanvas(e);cbPointers.set(e.pointerId,p);c.setPointerCapture?.(e.pointerId);if(cbPointers.size>=2){if(!cbPinch&&!cbGestureLock)cbBeginPinch(w,h);cbUpdatePinch(w,h);return}if(cbGestureLock)return;if(cbScreen==='select'){cbDrag={select:true,state:'routing',pointerId:e.pointerId,pointerType:e.pointerType||'mouse',rawInput:[{...p}],lastPointer:p};cbSelectAt(p,w,h);return}if(!cbCircuit||cbCircuit.complete)return;const start=cbCircuit.sequence.at(-1),sp=cbNodePx(start,w,h),returning=cbReturnPhase(),reach=e.pointerType==='touch'?42:34;if(!sp||(!returning&&Math.hypot(p.x-sp.x,p.y-sp.y)>reach)){$('cbBoardHint').textContent=returning?'Drag toward the green-ring FAP':'Start on the green-ring device';return}cbDrag={points:[sp],previewLegs:[],targets:[],from:start,routeAxis:null,turnAnchor:null,routeInput:sp,routeDir:0,pendingTurnDir:0,pendingTurnSamples:0,intentInput:sp,rawInput:[{...p}],state:returning?'returning':'routing',pointerId:e.pointerId,pointerType:e.pointerType||'mouse',lastPointer:returning?sp:p,returnMode:returning,returnProgress:0,returnGuide:null};if(returning){cbAppendReturnDrag(p,w,h);cbDrag.lastPointer=p;$('cbBoardHint').textContent='Return to the green-ring FAP · magnetic twin cable is on';}cbHover=null}''')
a="const challenge=cbScreen==='game'&&cbCircuit?.type==='conventional',pairBadge=$('cbPairBadge'),pairMode=cbScreen==='game'&&!!cbCircuit,blocked=!!(challenge&&cbDrag?.blocked),returning=cbScreen==='game'&&cbReturnPhase();if(pairBadge){";b="const challenge=cbScreen==='game'&&cbCircuit?.type==='conventional',pairBadge=$('cbPairBadge'),pairMode=cbScreen==='game'&&!!cbCircuit,blocked=!!(challenge&&cbDrag?.blocked),returning=cbScreen==='game'&&cbReturnPhase(),routeState=cbRoutingState();if(pairBadge){";t=rep(t,a,b,'paint state')
a="pairBadge.hidden=!pairMode;pairBadge.classList.toggle('on',!!(returning||(pairMode&&cbDrag?.pairSnap&&!blocked)));pairBadge.classList.toggle('blocked',blocked);pairBadge.textContent=blocked?'✕ NO CROSSING':returning?'⇄ RETURN MAGNET · FOLLOW CABLE':pairMode&&cbDrag?.pairSnap?'⇄ CABLES PAIRED':challenge?'GRID '+gridStep()+' · NO CROSSING':'⇄ TWIN CABLE · GRID '+gridStep()}";b="pairBadge.hidden=!pairMode;pairBadge.classList.toggle('on',!!(returning||(pairMode&&cbDrag?.pairSnap&&!blocked)));pairBadge.classList.toggle('blocked',blocked);pairBadge.classList.toggle('pending',routeState==='corner-pending');pairBadge.textContent=blocked?'✕ NO CROSSING':returning?'⇄ RETURN MAGNET · FOLLOW CABLE':pairMode&&cbDrag?.pairSnap?'⇄ CABLES PAIRED':routeState==='corner-pending'?'↳ CORNER READY · GRID '+gridStep():routeState==='device-captured'?'✓ DEVICE CAPTURED · GRID '+gridStep():challenge?'SMART ROUTE · GRID '+gridStep()+' · NO CROSSING':'⇄ TWIN CABLE · SMART ROUTE · GRID '+gridStep()+' · CORRIDOR'}";t=rep(t,a,b,'badge')
t=rep(t,"'Hold on the green-ring device and drag through detectors · cable uses Survey field grid · corners lock cleanly · the final return magnetically follows the outgoing cable · pinch with two fingers to zoom'","'Start on the green-ring device and drag naturally · the device corridor catches fast passes · Smart Route filters finger wobble into clean grid cable · the final return magnetically follows the outgoing cable · pinch with two fingers to zoom'",'hint')
t=rep(t,'</style>',"\n.cbPairBadge.pending{border-color:#d39b3f88;background:#fff7e8;color:#8a5b12;box-shadow:0 0 0 4px #d99b3214,0 6px 22px #8d641c18}\n</style>",'css')
INDEX.write_text(t)
for p in ['ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html']:(ROOT/p).write_text(t)
g=ROOT/'app/build.gradle';g.write_text(g.read_text().replace('versionCode 57','versionCode 58').replace("versionName '0.56'","versionName '0.57'"))
p=ROOT/'tests/circuit-retrace-v053.cjs';s=p.read_text().replace("assert.match(html,/if\\(!captured\\)cbAppendDrag\\(p,w,h\\)/,'detector capture must discard the sparse touch tail');","assert.match(html,/function cbRouteIntentPoint/,'raw touch must be filtered separately from drawn geometry after detector capture');");p.write_text(s)
p=ROOT/'tests/circuit-zone-game-v054.cjs';p.write_text(p.read_text().replace("/v0\\.(?:54|55|56)/","/v0\\.(?:54|55|56|57)/"))
p=ROOT/'tests/circuit-aggressive-touch-v057.cjs';s=p.read_text().replace("const phase=process.env.ROUTING_PHASE||'baseline';","const phase=process.env.ROUTING_PHASE||'regression';")
needle="  assert(report.noisy.points<=base.noisy.points,'noisy traces must use no more route points than baseline');\n }\n console.log(`PASS: ${phase} aggressive-touch replay across ${viewports.length} viewports × ${Object.keys(styles).length} deterministic traces`);"
add="  assert(report.noisy.points<=base.noisy.points,'noisy traces must use no more route points than baseline');\n  assert(report.noisy.reversals<=Math.floor(base.noisy.reversals*.55),'Smart Route must cut noisy immediate reversals by at least 45%');\n  assert.equal(report.noisy.intersections,0,'Smart Route must remove noisy self-intersections');\n }else if(phase==='regression'){\n  assert.equal(report.aggregate.devicesCaptured,report.aggregate.totalDevices,'all deterministic traces must capture every device');\n  assert.equal(report.aggregate.complete,report.aggregate.cases,'all deterministic traces must complete');\n  assert.equal(report.noisy.intersections,0,'aggressive touch must not self-intersect');\n  assert(report.noisy.reversals<=38,`too many noisy immediate reversals: ${report.noisy.reversals}`);\n  assert(report.noisy.corners<=132,`too many noisy corners: ${report.noisy.corners}`);\n  assert(report.noisy.points<=330,`too many noisy route points: ${report.noisy.points}`);\n  assert(report.noisy.excessRatio<=1.52,`noisy route length is too inflated: ${report.noisy.excessRatio}`);\n }\n console.log(`PASS: ${phase} aggressive-touch replay across ${viewports.length} viewports × ${Object.keys(styles).length} deterministic traces`);"
if needle not in s: raise SystemExit('aggressive gate anchor missing')
p.write_text(s.replace(needle,add))
p=ROOT/'tests/run-regressions.cjs';s=p.read_text().replace('// v0.56 suite includes the magnetic return regression and the updated Zone Challenge compatibility gate.','// v0.57 suite adds deterministic aggressive-touch replay and explicit Smart Route state-machine coverage.').replace("'circuit-return-magnet-v056'","'circuit-return-magnet-v056','circuit-routing-state-v057','circuit-aggressive-touch-v057'");p.write_text(s)
print('Applied Zone Sketch v0.57 Smart Route generation upgrade')
