const fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium,webkit}=require('playwright');
const source=fs.readFileSync('index.html','utf8'),anchor="document.querySelector('.app').inert=true;\nensureUiState();",html=source.replace(anchor,"window.batchTest={get:()=>clone(),busy:()=>projectBusy,saveNow,screenPoint,connectionPath,mutate:fn=>{fn(state);changed()},undo:doUndo,redo:doRedo,view:()=>({tool,navMode,selection}),filter:()=>{recordFilter=new Set(['verified']);draw()}};"+anchor);assert.notEqual(html,source);
const server=http.createServer((req,res)=>{try{const file=(req.url||'/').split('?')[0].slice(1)||'index.html';res.end(file==='index.html'?html:fs.readFileSync(file))}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');
(async()=>{await new Promise(r=>server.once('listening',r));const browser=await(process.env.BROWSER==='webkit'?webkit:chromium).launch();try{
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.AndroidBridge={shareFile:(data,name,mime)=>window.shared={data,name,mime}});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!document.querySelector('#homeNew').disabled);
const open=async()=>{await page.evaluate(()=>document.querySelector('#surveyDevice').click());await page.locator('#batchDeviceOpen').tap();await page.locator('#batchDeviceModal.open').waitFor()};
const read=()=>page.evaluate(()=>batchTest.get());
for(const [system,types] of Object.entries({fire:['smoke','heat'],security:['secPir','secDoorContact'],cctv:['cctvFixed','cctvSwitch'],access:['accessReader','accessMaglock']})){
await page.locator('.homeSystemTile[data-system="'+system+'"]').tap();await page.locator('#newProjectName').fill('Batch '+system);await page.locator('#newProjectCreate').tap();await page.locator('#projectsHome').waitFor({state:'hidden'});
if(system==='fire'){await page.evaluate(()=>document.querySelector('#symbolMenuBtn').click());await page.locator('#batchDeviceOpen').tap();assert.equal(await page.locator('#batch-smoke').count(),0);await page.locator('#batchDeviceCancel').tap()}
await page.evaluate(()=>document.querySelector('#surveyModeBtn').click());await page.evaluate(()=>batchTest.mutate(s=>s.symbols.push({id:'old-device',type:s.systemType==='fire'?'panel':s.systemType==='security'?'secPanel':s.systemType==='cctv'?'cctvNvr':'accessAcu',x:.5,y:.5,scope:'survey',scale:1,reference:'EXISTING',recordState:{state:'existing'}})));await page.evaluate(()=>batchTest.filter());await open();assert(await page.locator('#batchDeviceAdd').isDisabled());
await page.locator('#batch-'+types[0]).fill('2');await page.locator('#batch-'+types[1]).fill('1');await page.locator('#batch-'+types[0]).fill('1.5');assert(await page.locator('#batchDeviceAdd').isDisabled());await page.locator('#batch-'+types[0]).fill('100');assert(await page.locator('#batchDeviceAdd').isDisabled());await page.locator('#batch-'+types[0]).fill('2');
if(system==='fire'){for(const [width,height] of [[320,568],[390,844],[412,915],[768,1024],[1280,800]]){await page.setViewportSize({width,height});await page.locator('#batchDeviceModal .box').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));const modal=await page.locator('#batchDeviceModal .box').boundingBox(),add=await page.locator('#batchDeviceAdd').boundingBox();assert(modal.x>=0&&modal.x+modal.width<=width+1);assert(add.height>=44&&add.y>=0&&add.y+add.height<=height);const plus=page.getByRole('button',{name:'More Smoke',exact:true});await plus.scrollIntoViewIfNeeded();const rect=await plus.boundingBox();assert(rect.width>=44&&rect.height>=44);assert(await page.locator('#batchDeviceRows').evaluate(e=>e.scrollWidth<=e.clientWidth+1));if(width===390)await page.screenshot({path:'/tmp/batch-devices-phone.png'})}await page.setViewportSize({width:390,height:844})}
await page.locator('#batchDeviceAdd').tap();await page.locator('#batchDeviceModal').waitFor({state:'hidden'});let p=await read();assert.equal(p.symbols.length,4);const added=p.symbols.filter(s=>s.id!=='old-device');assert.equal(new Set(added.map(s=>s.id)).size,3);assert.equal(new Set(added.map(s=>s.x+','+s.y)).size,3);assert(added.every(s=>!s.group&&s.scope==='survey'&&s.recordState.state==='notRecorded'));assert.deepEqual(await page.evaluate(()=>batchTest.view()),{tool:'select',navMode:false,selection:[]});assert.equal(p.symbols[0].reference,'EXISTING');assert(added.every(s=>s.x!==.5||s.y!==.5));
await page.evaluate(()=>batchTest.undo());assert.equal((await read()).symbols.length,1);await page.evaluate(()=>batchTest.redo());assert.deepEqual((await read()).symbols.map(s=>s.id),p.symbols.map(s=>s.id));
// Drag an ordinary individual symbol; the others and all IDs stay unchanged.
const first=added[0],before=await read();await page.evaluate(id=>batchTest.mutate(s=>s.connections.push({id:'batch-link',systemType:s.systemType,sourceId:id,targetId:'old-device',connectionType:'Circuit',route:[],metadata:{}})),first.id);const pt=await page.evaluate(id=>batchTest.screenPoint(batchTest.get().symbols.find(s=>s.id===id)),first.id),canvas=await page.locator('#canvas').boundingBox();await page.mouse.move(canvas.x+pt.x,canvas.y+pt.y);await page.mouse.down();await page.mouse.move(canvas.x+pt.x+45,canvas.y+pt.y+25,{steps:6});await page.mouse.up();p=await read();const moved=p.symbols.find(s=>s.id===first.id);assert(moved.x!==first.x||moved.y!==first.y);for(const item of before.symbols.filter(s=>s.id!==first.id))assert.deepEqual(p.symbols.find(s=>s.id===item.id),item);const start=await page.evaluate(()=>{const p=batchTest.get();return batchTest.connectionPath(p.connections[0],p)[0]});assert.deepEqual(start,{x:moved.x,y:moved.y});
if(system==='fire'){await open();await page.locator('#batch-smoke').fill('100');await page.locator('#batchDeviceAdd').tap();assert.equal((await read()).symbols.length,104);assert.equal(new Set((await read()).symbols.map(s=>s.id)).size,104);await page.evaluate(()=>batchTest.undo());assert.deepEqual((await read()).symbols,p.symbols)}await page.evaluate(()=>batchTest.saveNow());await page.reload();await page.waitForFunction(()=>!document.querySelector('#homeNew').disabled);await page.locator('.projectCard').filter({has:page.getByRole('heading',{name:'Batch '+system,exact:true})}).getByRole('button',{name:'Open',exact:true}).tap();assert.deepEqual((await read()).symbols,p.symbols);await page.waitForFunction(()=>!batchTest.busy());await page.evaluate(()=>document.querySelector('#headerHomeBtn').click());await page.locator('#projectsHome').waitFor({state:'visible'});const card=page.locator('.projectCard').filter({has:page.getByRole('heading',{name:'Batch '+system,exact:true})});await page.evaluate(()=>window.shared=null);await card.getByRole('button',{name:'Export',exact:true}).tap();await page.waitForFunction(()=>window.shared?.mime==='application/json');const backup=await page.evaluate(()=>JSON.parse(decodeURIComponent(escape(atob(window.shared.data.split(',')[1])))));assert.deepEqual(backup.project.floors[0].data.symbols,p.symbols);await page.waitForFunction(()=>!batchTest.busy());
}
assert.deepEqual(errors,[]);console.log('PASS batch devices: four systems, mixed quantities, validation, five viewports, independent drag, attached route, undo/redo IDs, legacy item, reload and backup export');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exit(1)});
