const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>{const path=(q.url||'/').split('?')[0],file=path==='/'?'index.html':path.slice(1);try{const data=fs.readFileSync(file);r.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.pdf')?'application/pdf':'text/html');r.end(data)}catch(e){r.statusCode=404;r.end('not found')}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true});try{const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept(d.type()==='prompt'?'School':undefined));await p.goto('http://127.0.0.1:'+server.address().port);await p.locator('#homeNew').click();await p.locator('#projectsHome').waitFor({state:'hidden'});
assert.equal(await p.locator('.favouriteQuick').count(),6);assert.deepEqual(await p.locator('.favouriteQuick').allTextContents(),['Panel','Repeater','You are here','Door','Wall','Pinned note']);
await p.locator('.favouriteQuick').filter({hasText:'Panel'}).click();const box=await p.locator('#canvas').boundingBox();await p.mouse.click(box.x+box.width/2,box.y+box.height/2);assert.equal(await p.locator('.favouriteQuick.active').textContent(),'Panel');
await p.locator('#favouriteMenuBtn').click();await p.locator('[data-favourite-choice="tool:stairs"]').click();assert.equal(await p.locator('.favouriteQuick').count(),7);assert(await p.locator('.favouriteQuick').filter({hasText:'Stairs'}).isVisible());
// Holding a menu item toggles it without activating the tool.
await p.locator('#layoutMenuBtn').click();const pen=p.locator('[data-menu-tool="pen"]');await pen.dispatchEvent('pointerdown',{button:0});await p.waitForTimeout(680);await pen.dispatchEvent('pointerup',{button:0});await pen.dispatchEvent('click');assert(await p.locator('.favouriteQuick').filter({hasText:'Pen'}).isVisible());assert.notEqual(await p.locator('.favouriteQuick.active').textContent(),'Pen');
// Favourites are a device preference and survive project/reload changes.
await p.reload();await p.locator('#resumeProject').click();assert.equal(await p.locator('.favouriteQuick').count(),8);assert(await p.locator('.favouriteQuick').filter({hasText:'Stairs'}).isVisible());assert(await p.locator('.favouriteQuick').filter({hasText:'Pen'}).isVisible());
await p.locator('#favouriteMenuBtn').click();await p.locator('#resetFavourites').click();assert.equal(await p.locator('.favouriteQuick').count(),6);
await p.locator('#surveyModeBtn').click();assert(await p.locator('#favouriteMenuBtn').isHidden());await p.locator('#surveyModeBtn').click();assert(await p.locator('#favouriteMenuBtn').isVisible());
await p.screenshot({path:'test-results/favourites-phone.png'});await p.setViewportSize({width:1024,height:768});await p.screenshot({path:'test-results/favourites-tablet.png'});assert.deepEqual(errors,[]);console.log('PASS: favourite defaults, activation, manager, hold-to-add, persistence, reset, survey-mode hiding and responsive layout');}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
