const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>r.end(fs.readFileSync('index.html'))).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1024,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.addInitScript(()=>window.AndroidBridge={sharePng:(data,name)=>window.exported={data,name}});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForTimeout(250);await page.locator('#projectMenuBtn').click();await page.locator('#blankBtn').click();await page.locator('#site').fill('School');const b=await page.locator('#canvas').boundingBox();await page.mouse.move(b.x+100,b.y+100);await page.mouse.down();await page.mouse.move(b.x+350,b.y+100,{steps:5});await page.mouse.up();
const saved=async()=>{await page.waitForTimeout(550);return page.evaluate(()=>new Promise(ok=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const g=r.result.transaction('draft').objectStore('draft').get('state');g.onsuccess=()=>ok(g.result)}}))};
assert.equal((await saved()).walls.length,1);
await page.locator('#floorMenuBtn').click();await page.locator('#addFloor').click();assert.equal(await page.locator('#floorPreset').inputValue(),'First floor');await page.locator('#floorCopy').check();await page.locator('#saveFloor').click();assert.equal((await saved()).walls.length,1);assert.equal((await saved()).site,'School');
await page.locator('#projectMenuBtn').click();await page.locator('#blankBtn').click();assert.equal((await saved()).walls.length,0);const opts=await page.locator('#floorSelect option').evaluateAll(os=>os.map(o=>o.value));await page.locator('#floorMenuBtn').click();await page.locator('.floorChoice').nth(0).click();assert.equal((await saved()).walls.length,1);await page.locator('#floorMenuBtn').click();await page.locator('.floorChoice').nth(1).click();assert.equal((await saved()).walls.length,0);
await page.locator('#floorMenuBtn').click();await page.locator('#addFloor').click();await page.locator('#saveFloor').click();assert.equal(await page.locator('#floorSelect option').count(),3);await page.locator('#shareBtn').click();await page.locator('#exportPng').click();await page.waitForFunction(()=>window.exported?.data);assert.match(await page.evaluate(()=>exported.name),/Second-floor/);await page.locator('#floorMenuBtn').click();await page.locator('#deleteFloor').click();await page.waitForFunction(()=>document.querySelectorAll('#floorSelect option').length===2);assert.equal(await page.locator('#floorSelect option').count(),2);await page.locator('#undo').click();assert.equal(await page.locator('#floorSelect option').count(),3);await saved();await page.reload();await page.waitForTimeout(500);assert.equal(await page.locator('#floorSelect option').count(),3);assert.equal(await page.locator('#floorSelect option:checked').textContent(),'Second floor');
await page.setViewportSize({width:390,height:844});fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/floors-phone.png'});assert.deepEqual(errors,[]);
// Migrate a legacy single-floor draft without dropping the drawing.
await page.evaluate(()=>new Promise(ok=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('draft','readwrite'),s=t.objectStore('draft'),g=s.get('state');g.onsuccess=()=>{const v=g.result;delete v.floors;delete v.activeFloor;v.notes=[{x:.5,y:.5,text:'legacy note'}];s.put(v,'state')};t.oncomplete=ok}}));await page.reload();await page.waitForTimeout(500);assert.equal(await page.locator('#floorSelect option').count(),1);assert.equal((await saved()).notes[0].text,'legacy note');assert.deepEqual(errors,[]);console.log('PASS: floor copy, isolation, blank floor, undo deletion, export filename, reload, legacy migration and mobile rendering');}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});

