const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>r.end(fs.readFileSync('index.html'))).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true});try{
const p=await browser.newPage({viewport:{width:1180,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept(d.type()==='prompt'?'Test note':undefined));await p.addInitScript(()=>window.AndroidBridge={sharePng:(data,name)=>window.exported={data,name},shareFile:(data,name,mime)=>window.shared={data,name,mime}});await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForTimeout(150);await p.locator('#emptyBlank').click();await p.locator('#site').fill('Riverside Works');
const saved=async()=>{await p.waitForTimeout(450);return p.evaluate(()=>new Promise(ok=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const db=r.result,g=db.transaction('draft').objectStore('draft').get('state');g.onsuccess=()=>{ok(g.result);db.close()}}}))};
const xy=async(x,y)=>p.locator('#canvas').evaluate((c,{x,y})=>{const b=c.getBoundingClientRect(),s=Math.min((b.width-48)/3200,(b.height-48)/2000);return{x:b.x+b.width/2+(x-.5)*3200*s,y:b.y+b.height/2+(y-.5)*2000*s}},{x,y});
const click=async(x,y)=>{const a=await xy(x,y);await p.mouse.click(a.x,a.y)};const drag=async(x1,y1,x2,y2)=>{const a=await xy(x1,y1),b=await xy(x2,y2);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:12});await p.mouse.up()};const tool=async(menu,t)=>{await p.locator('#'+menu+'MenuBtn').click();await p.locator('[data-menu-tool="'+t+'"]').click()};
// Draw a room, colour it and install a real door in its top wall.
await tool('layout','layoutRect');await drag(.15,.2,.75,.7);await p.locator('#zoneMenuBtn').click();await p.locator('#zoneCreate').click();await p.locator('#zoneName').fill('Workshop');await p.locator('#saveZone').click();await tool('zone','rect');await drag(.15,.2,.75,.7);await tool('object','door');await drag(.35,.2,.45,.2);let d=await saved();assert.equal(d.doors.length,1);assert.equal(d.walls.length,5);
// Delete by tapping the swing arc, not the opening. Zone and both wall stubs survive.
await p.locator('#deleteTop').click();await click(.35+.1/Math.sqrt(2),.2+.16/Math.sqrt(2));d=await saved();assert.equal(d.doors.length,0);assert.equal(d.walls.length,5);assert.equal(d.shapes.length,1);
await p.locator('#undoTop').click();d=await saved();assert.equal(d.doors.length,1);assert.equal(d.walls.length,5);
// The leaf is independently selectable; Properties delete leaves the gap too.
await p.locator('[data-tool="select"]').click();await click(.35,.28);await p.locator('#propertiesSelected').click();assert.equal(await p.locator('#propKind').textContent(),'Door');await p.locator('#propDelete').click();d=await saved();assert.equal(d.doors.length,0);assert.equal(d.walls.length,5);await p.locator('#undoTop').click();
// Room-name stamps, symbol repeats and device references.
await p.locator('#layoutMenuBtn').click();await p.locator('[data-room-name="Office"]').click();await click(.29,.48);await click(.55,.48);assert.equal((await saved()).labels.length,2);
await p.locator('#symbolMenuBtn').click();await p.locator('[data-symbol="beacon"]').click();await click(.3,.36);await click(.6,.36);assert.equal((await saved()).symbols.length,2);
await p.locator('[data-tool="select"]').click();await click(.3,.36);await p.locator('#propertiesSelected').click();await p.locator('#propDevice').fill('L1-025');await p.locator('#propSave').click();assert.equal((await saved()).symbols[0].reference,'L1-025');
// Locks block stamps on pointer-up as well as pointer-down.
await p.locator('#locksMenuBtn').click();await p.locator('[data-lock="building"]').click();await p.locator('#locksMenuBtn').click();await p.locator('#layoutMenuBtn').click();await p.locator('[data-room-name="Office"]').click();await click(.7,.6);assert.equal((await saved()).labels.length,2);await p.locator('#locksMenuBtn').click();await p.locator('[data-lock="building"]').click();await p.locator('#locksMenuBtn').click();
// Multi-touch in edit mode must not stamp either touch.
await p.locator('#symbolMenuBtn').click();await p.locator('[data-symbol="smoke"]').click();const a=await xy(.6,.6);// Real touch events are tested via CDP to provide valid pointer capture IDs.
const session=await p.context().newCDPSession(p);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x,y:a.y,id:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x,y:a.y,id:1},{x:a.x+40,y:a.y,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal((await saved()).symbols.length,2);
// Photo pin has a real image and a caption; Properties previews it.
await p.locator('#detailMenuBtn').click();await p.locator('[data-detail-tool="pinPhoto"]').click();await click(.63,.58);const svg='<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200"><rect width="300" height="200" fill="#cc5544"/><text x="20" y="80" fill="white">Survey photo</text></svg>';await p.locator('#pinPhotoFile').setInputFiles({name:'survey.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await p.waitForTimeout(250);d=await saved();assert.equal(d.pins.length,1);assert.equal(d.pins[0].kind,'photo');await p.locator('[data-tool="select"]').click();await click(.63,.58);await p.locator('#propertiesSelected').click();assert.equal(await p.locator('#propPhoto').isVisible(),true);await p.locator('#propClose').click();
// Group duplication, rigid move and cancelled drag restore original coordinates.
await p.locator('[data-tool="group"]').click();await drag(.11,.14,.8,.76);await p.locator('#groupSelected').click();let original=await saved();await p.locator('#duplicateSelected').click();d=await saved();assert.equal(d.doors.length,2);assert.equal(d.symbols.length,4);await p.locator('#undoTop').click();
await p.locator('[data-tool="select"]').click();await click(.15,.45);const before=await saved();await drag(.15,.45,.02,.45);d=await saved();const span=o=>Math.max(...o.walls.flatMap(w=>w.points.map(p=>p.x)))-Math.min(...o.walls.flatMap(w=>w.points.map(p=>p.x)));assert(Math.abs(span(before)-span(d))<.00001,'Dragging to edge keeps room width');await p.locator('#undoTop').click();
// Floor dropdown uses in-app buttons. Metadata flows into an all-floor PDF.
await p.locator('#floorMenuBtn').click();assert.equal(await p.locator('#floorSelect').isVisible(),false);await p.locator('#addFloor').click();await p.locator('#floorCopy').check();await p.locator('#saveFloor').click();await saved();await p.locator('#floorMenuBtn').click();await p.locator('.floorChoice').first().click();await saved();await p.locator('#projectMenuBtn').click();await p.locator('#drawingDetails').click();await p.locator('#drawingRef').fill('RW-001');await p.locator('#revision').fill('A');await p.locator('#surveyedBy').fill('Will');await p.locator('#detailsSave').click();
await p.locator('#shareBtn').click();await p.locator('#exportPdf').click();await p.waitForFunction(()=>window.shared?.mime==='application/pdf');let pdf=await p.evaluate(()=>window.shared);fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/building.pdf',Buffer.from(pdf.data.split(',')[1],'base64'));assert.match(pdf.name,/all-floors.pdf$/);
await p.locator('#shareBtn').click();await p.locator('#exportBackup').click();await p.waitForFunction(()=>window.shared?.mime==='application/json');const backup=await p.evaluate(()=>window.shared);const json=Buffer.from(backup.data.split(',')[1],'base64');assert.equal(JSON.parse(json).project.floors.length,2);
await p.locator('#projectMenuBtn').click();await p.locator('#newBtn').click();await saved();await p.locator('#projectFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:json});await p.waitForFunction(()=>document.querySelectorAll('.floorChoice').length===2);d=await saved();assert.equal(d.meta.drawingRef,'RW-001');assert.equal(d.pins[0].kind,'photo');assert.equal(d.symbols[0].reference,'L1-025');
// Reject invalid backup without changing the site.
await p.locator('#projectFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"bad"}')});assert.equal((await saved()).site,'Riverside Works');
await p.locator('#shareBtn').click();await p.locator('#exportPng').click();await p.waitForFunction(()=>window.exported?.data);const png=await p.evaluate(()=>window.exported.data);fs.writeFileSync('test-results/floor-export.png',Buffer.from(png.split(',')[1],'base64'));
await p.screenshot({path:'test-results/survey-tablet.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'test-results/survey-phone.png'});await p.locator('#floorMenuBtn').click();const box=await p.locator('#floorMenu').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=390&&box.y+box.height<=844);await p.screenshot({path:'test-results/floors-phone.png'});await p.locator('#floorMenuBtn').click();await p.locator('#symbolMenuBtn').click();const sb=await p.locator('#symbolMenu').boundingBox();assert(sb.y>=0&&sb.y+sb.height<=844);await p.screenshot({path:'test-results/symbols-phone.png'});
assert.deepEqual(errors,[]);console.log('PASS: door arc/leaf deletion, undo, stamps, locks, multitouch, photo preview, groups, edge movement, PDF, backup restore, invalid backup and mobile menus');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
