const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>{const path=(q.url||'/').split('?')[0],file=path==='/'?'index.html':path.slice(1);try{const data=fs.readFileSync(file);r.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.pdf')?'application/pdf':'text/html');r.end(data)}catch(e){r.statusCode=404;r.end('not found')}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true});try{
const p=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept(d.type()==='prompt'?'Resize this note':undefined));await p.goto('http://127.0.0.1:'+server.address().port);await p.locator('#homeNew').click();await p.locator('#projectsHome').waitFor({state:'hidden'});if(await p.locator('#emptyBlank').isVisible())await p.locator('#emptyBlank').click();await p.waitForTimeout(100);
const box=await p.locator('#canvas').boundingBox(),cx=box.x+box.width*.55,cy=box.y+box.height*.45;
await p.locator('[data-tool="note"]').click();await p.mouse.click(cx,cy);await p.waitForTimeout(100);
await p.locator('[data-tool="select"]').click();await p.mouse.click(cx,cy);await p.locator('#selectionBar').waitFor({state:'visible'});await p.locator('#propertiesSelected').click();await p.locator('#propertyModal').waitFor({state:'visible'});assert.equal(await p.locator('#propKind').textContent(),'Note');assert.equal(await p.locator('#propScaleWrap').isVisible(),true,'note must expose Size in Properties');
await p.locator('#propScale').evaluate(el=>{el.value='0.5';el.dispatchEvent(new Event('input',{bubbles:true}))});assert.equal(await p.locator('#propScaleValue').textContent(),'0.50×');await p.locator('#propSave').click();
await p.waitForTimeout(650);const note=await p.evaluate(()=>new Promise(ok=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const db=r.result,g=db.transaction('draft').objectStore('draft').get('state');g.onsuccess=()=>{const s=g.result,f=s.floors.find(x=>x.id===s.activeFloor);ok((f?.data?.notes||s.notes)[0]);db.close()}}}));assert.equal(note.text,'Resize this note');assert.equal(note.scale,.5,'chosen note size must persist');
await p.reload();await p.locator('#resumeProject').click();await p.waitForTimeout(100);const restored=await p.evaluate(()=>new Promise(ok=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const db=r.result,g=db.transaction('draft').objectStore('draft').get('state');g.onsuccess=()=>{const s=g.result,f=s.floors.find(x=>x.id===s.activeFloor);ok((f?.data?.notes||s.notes)[0]);db.close()}}}));assert.equal(restored.scale,.5,'note size must survive reload');
fs.mkdirSync('test-results',{recursive:true});await p.screenshot({path:'test-results/note-size.png'});assert.deepEqual(errors,[]);console.log('PASS: note Size control saves and persists across reload');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
