const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>r.end(fs.readFileSync('index.html'))).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true});try{
const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];let answer='School';p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept(d.type()==='prompt'?answer:undefined));await p.addInitScript(()=>window.AndroidBridge={shareFile:(data,name,mime)=>window.shared={data,name,mime}});
const url='http://127.0.0.1:'+server.address().port;await p.goto(url);await p.locator('#homeNew').click();await p.locator('#projectsHome').waitFor({state:'hidden'});
await p.locator('#floorMenuBtn').click();await p.locator('#addFloor').click();await p.locator('#saveFloor').click();
const cardCount=async n=>p.waitForFunction(n=>document.querySelectorAll('.projectCard').length===n,n);const home=async()=>{await p.locator('#projectMenuBtn').click();await p.locator('#homeBtn').click();await p.locator('#projectsHome').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelectorAll('.projectCard').length>0)};
await home();assert.match(await p.locator('.projectCard').innerText(),/School[\s\S]*2 floors/);
answer='Warehouse';await p.locator('#homeNew').click();await p.locator('#projectsHome').waitFor({state:'hidden'});assert.equal(await p.locator('#floorSelect option').count(),1);assert(await p.locator('#undo').isDisabled());await home();await cardCount(2);
const card=name=>p.locator('.projectCard').filter({has:p.getByRole('heading',{name,exact:true})});
await card('School').getByRole('button',{name:'Duplicate',exact:true}).click();await cardCount(3);
answer='School copy renamed';await card('School (copy)').getByRole('button',{name:'Rename',exact:true}).click();await card(answer).waitFor();await card(answer).getByRole('button',{name:'Open',exact:true}).click();await p.locator('#projectsHome').waitFor({state:'hidden'});assert.equal(await p.locator('#floorSelect option').count(),2);assert(await p.locator('#undo').isDisabled());await home();
await card(answer).getByRole('button',{name:'Export',exact:true}).click();await p.waitForFunction(()=>window.shared);const backup=await p.evaluate(()=>JSON.parse(atob(window.shared.data.split(',')[1])));assert.equal(backup.project.site,answer);assert.equal(backup.project.floors.length,2);
await card(answer).getByRole('button',{name:'Delete',exact:true}).click();await cardCount(2);await p.reload();await card('School').waitFor();assert.equal(await p.locator('.projectCard').count(),2);
await p.locator('#projectFile').setInputFiles({name:'survey.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.locator('#projectsHome').waitFor({state:'hidden'});await home();assert.equal(await p.locator('.projectCard').count(),3);
await p.screenshot({path:'test-results/projects-phone.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
// Invalid imports leave every project intact.
await p.locator('#projectFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});await p.waitForTimeout(100);assert.equal(await p.locator('.projectCard').count(),3);
// A failed save must keep the current survey open instead of switching away.
await card('School').getByRole('button',{name:'Open',exact:true}).click();await p.locator('#projectsHome').waitFor({state:'hidden'});await p.evaluate(()=>{window.originalTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){if(args[1]==='readwrite')throw Error('Simulated storage failure');return window.originalTransaction.apply(this,args)}});await p.locator('#site').fill('Unsaved school');await p.locator('#projectMenuBtn').click();await p.locator('#homeBtn').click();assert(await p.locator('#projectsHome').isHidden());assert.equal(await p.locator('#site').inputValue(),'Unsaved school');await p.evaluate(()=>IDBDatabase.prototype.transaction=window.originalTransaction);
assert.deepEqual(errors,[]);console.log('PASS: project isolation, rename, duplicate, export, delete, reload, import, invalid import, failed-save protection and phone layout');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
