const fs=require('node:fs'),assert=require('node:assert/strict');
const copies=['index.html','ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html'];
const html=copies.map(p=>fs.readFileSync(p,'utf8'));
for(let i=1;i<html.length;i++)assert.equal(html[i],html[0],`${copies[i]} must match index.html byte-for-byte`);
const app=html[0];
assert(app.includes('Zone Sketch by Will Flood v0.63'),'document title must be v0.63');
assert(app.includes('BETA v0.63'),'visible app badge must be v0.63');
assert(!app.includes('BETA v0.62'),'stale visible v0.62 badge remains');
assert(app.includes('function combinedBuildMode()'),'Build/Pan integration predicate must ship');
assert(app.includes("b.disabled=combined"),'combined Build mode must disable the old Pan control');
assert(app.includes("combined?'Pan · 2 fingers'"),'combined mode must explain two-finger navigation');
assert(app.includes("!surveyMode&&!navMode&&!combinedBuildMode()"),'combined mode must preserve two-finger navigation instead of cancelling it');
assert(app.includes('function combinedZoneAt(clientX,clientY)'),'combined zone hit logic must remain present');
assert(app.includes("combinedZone:true"),'combined zone drag path must remain present');
assert(app.includes('ZONE SKETCH · <b>v0.63</b>'),'App settings footer must match the current release');
assert(app.includes('id="cbFloorSelect"'),'multi-floor Circuit Builder must remain present');
assert(app.includes('function cbRepairConventionalRefs'),'circuit reference recovery must remain present');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(/versionCode\s+64\b/.test(gradle),'Android versionCode must be 64');
assert(/versionName\s+'0\.63'/.test(gradle),'Android versionName must be 0.63');
const beta=fs.readFileSync('beta.html','utf8');
assert(beta.includes('Web v0.63'),'beta portal must show Web v0.63');
assert(beta.includes('Android v0.63'),'beta portal must show Android v0.63');
assert(beta.includes('releases/download/v0.63/Zone-Sketch-by-Will-v0.63.apk'),'beta portal must target the v0.63 release asset');
assert(beta.includes('downloads/Zone-Sketch-by-Will-v0.63.apk'),'beta portal must retain the backup APK mirror');
assert(beta.includes('./web-v063.html'),'beta portal must open the fresh v0.63 launcher');
assert(beta.includes('Build mode now really switches behaviour'),'beta portal must describe the integration fix');
const download=fs.readFileSync('download.html','utf8');
assert.equal(download,beta,'download.html and beta.html should not drift');
const launcher=fs.readFileSync('web-v063.html','utf8');
assert(launcher.includes('index.html?pineapple=v063&fresh='),'fresh launcher must target the v0.63 cache key');
const regressions=fs.readFileSync('tests/run-regressions.cjs','utf8');
assert(regressions.includes("'build-mode-v062'"),'v0.62 Build mode regression must remain in the full gate');
assert(regressions.includes("'build-mode-v063'"),'v0.63 Pan-conflict regression must be in the full gate');
console.log('PASS v0.63 release metadata, Build/Pan integration, regression parity and Android versioning');
