const fs=require('node:fs'),assert=require('node:assert/strict');
const copies=['index.html','ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html'];
const html=copies.map(p=>fs.readFileSync(p,'utf8'));
for(let i=1;i<html.length;i++)assert.equal(html[i],html[0],`${copies[i]} must match index.html byte-for-byte`);
assert(html[0].includes('Zone Sketch by Will Flood v0.59'), 'document title must be v0.59');
assert(html[0].includes('BETA v0.59'), 'visible app badge must be v0.59');
assert(!html[0].includes('BETA v0.58'), 'stale visible v0.58 badge remains');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(/versionCode\s+60\b/.test(gradle),'Android versionCode must be 60');
assert(/versionName\s+'0\.59'/.test(gradle),'Android versionName must be 0.59');
const beta=fs.readFileSync('beta.html','utf8');
assert(beta.includes('Web v0.59'),'beta portal must show Web v0.59');
assert(beta.includes('Android v0.59'),'beta portal must show Android v0.59');
assert(beta.includes('releases/download/v0.59/Zone-Sketch-by-Will-v0.59.apk'),'beta portal must target v0.59 release asset');
assert(beta.includes('downloads/Zone-Sketch-by-Will-v0.59.apk'),'beta portal must retain the backup APK mirror');
assert(beta.includes('./web-v059.html'),'beta portal must open the fresh v0.59 launcher');
const download=fs.readFileSync('download.html','utf8');
assert.equal(download,beta,'download.html and beta.html should not drift');
const launcher=fs.readFileSync('web-v059.html','utf8');
assert(launcher.includes('index.html?pineapple=v059&fresh='),'fresh launcher must target the v0.59 cache key');
console.log('PASS v0.59 release metadata, generated-copy parity, portal links and Android versioning');
