const fs=require('node:fs'),assert=require('node:assert/strict');
const copies=['index.html','ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html'];
const html=copies.map(p=>fs.readFileSync(p,'utf8'));
for(let i=1;i<html.length;i++)assert.equal(html[i],html[0],`${copies[i]} must match index.html byte-for-byte`);
const app=html[0];
assert(app.includes('Zone Sketch by Will Flood v0.63'),'document title must be v0.63');
assert(app.includes('BETA v0.63'),'visible app badge must be v0.63');
assert(!app.includes('BETA v0.62'),'stale visible v0.62 badge remains');
assert(app.includes('id="buildModeBtn"'),'v0.62 Build mode toggle must remain present');
assert(app.includes('id="zoneOpacity"'),'Drawing settings must ship the Zone tint slider');
assert(app.includes('function zoneTint(d=state)'),'zone tint normalisation must ship');
assert(app.includes('function syncZoneOpacity()'),'zone tint UI sync must ship');
assert(app.includes("'activeZoneId','zoneOpacity','pictureOpacity'"),'zone tint must persist per floor');
assert(app.includes("picked=combined&&!moved?getObj(selection[0]):null"),'combined mode tap-to-pick path must ship');
assert(app.includes("' picked · drag empty space to place it'"),'quick-pick feedback must ship');
assert(app.includes('id="cbFloorSelect"'),'v0.61 multi-floor Circuit Builder must remain present');
assert(app.includes('function cbRepairConventionalRefs'),'v0.60 circuit recovery must remain present');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(/versionCode\s+64\b/.test(gradle),'Android versionCode must be 64');
assert(/versionName\s+'0\.63'/.test(gradle),'Android versionName must be 0.63');
const beta=fs.readFileSync('beta.html','utf8');
assert(beta.includes('Web v0.63'),'beta portal must show Web v0.63');
assert(beta.includes('Android v0.63'),'beta portal must show Android v0.63');
assert(beta.includes('releases/download/v0.63/Zone-Sketch-by-Will-v0.63.apk'),'beta portal must target the v0.63 release asset');
assert(beta.includes('downloads/Zone-Sketch-by-Will-v0.63.apk'),'beta portal must retain the backup APK mirror');
assert(beta.includes('./web-v063.html'),'beta portal must open the fresh v0.63 launcher');
assert(beta.includes('Zone quick edit + tint'),'beta portal must describe the v0.63 milestone');
const download=fs.readFileSync('download.html','utf8');
assert.equal(download,beta,'download.html and beta.html should not drift');
const launcher=fs.readFileSync('web-v063.html','utf8');
assert(launcher.includes('index.html?pineapple=v063&fresh='),'fresh launcher must target the v0.63 cache key');
const regressions=fs.readFileSync('tests/run-regressions.cjs','utf8');
assert(regressions.includes("'build-mode-v062'"),'v0.62 build-mode regression must remain in the full gate');
assert(regressions.includes("'zone-quick-edit-v063'"),'v0.63 quick-edit regression must be in the full gate');
console.log('PASS v0.63 release metadata, Zone Plan quick-edit/tint regression parity and Android versioning');
