const fs=require('node:fs'),assert=require('node:assert/strict');
const copies=['index.html','ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html'];
const html=copies.map(p=>fs.readFileSync(p,'utf8'));
for(let i=1;i<html.length;i++)assert.equal(html[i],html[0],`${copies[i]} must match index.html byte-for-byte`);
const app=html[0];
assert(app.includes('Zone Sketch by Will Flood v0.61'),'document title must be v0.61');
assert(app.includes('BETA v0.61'),'visible app badge must be v0.61');
assert(!app.includes('BETA v0.60'),'stale visible v0.60 badge remains');
assert(app.includes('id="cbFloorSelect"'),'Circuit Builder floor selector must ship');
assert(app.includes('function cbSwitchFloor(id)'),'Circuit Builder floor switching logic must ship');
assert(app.includes("activeZoneId:null"),'per-floor selected zone state must ship');
assert(app.includes("'activeZoneId','pictureOpacity'"),'activeZoneId must be included in floor snapshots');
assert(app.includes('function changed(){syncFloor();'),'floor snapshots must update immediately when zone data changes');
assert(app.includes('function cbRepairConventionalRefs'),'v0.60 circuit recovery must remain present');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(/versionCode\s+62\b/.test(gradle),'Android versionCode must be 62');
assert(/versionName\s+'0\.61'/.test(gradle),'Android versionName must be 0.61');
const beta=fs.readFileSync('beta.html','utf8');
assert(beta.includes('Web v0.61'),'beta portal must show Web v0.61');
assert(beta.includes('Android v0.61'),'beta portal must show Android v0.61');
assert(beta.includes('releases/download/v0.61/Zone-Sketch-by-Will-v0.61.apk'),'beta portal must target the v0.61 release asset');
assert(beta.includes('downloads/Zone-Sketch-by-Will-v0.61.apk'),'beta portal must retain the backup APK mirror');
assert(beta.includes('./web-v061.html'),'beta portal must open the fresh v0.61 launcher');
assert(beta.includes('Floor-aware Circuit Builder'),'beta portal must describe the floor workflow milestone');
const download=fs.readFileSync('download.html','utf8');
assert.equal(download,beta,'download.html and beta.html should not drift');
const launcher=fs.readFileSync('web-v061.html','utf8');
assert(launcher.includes('index.html?pineapple=v061&fresh='),'fresh launcher must target the v0.61 cache key');
const regressions=fs.readFileSync('tests/run-regressions.cjs','utf8');
assert(regressions.includes("'floor-workflow-v061'"),'v0.61 floor regression must be in the full gate');
console.log('PASS v0.61 release metadata, multi-floor Circuit Builder, zone-state persistence, generated parity and Android versioning');
