const fs=require('node:fs'),assert=require('node:assert/strict');
const copies=['index.html','ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html'];
const html=copies.map(p=>fs.readFileSync(p,'utf8'));
for(let i=1;i<html.length;i++)assert.equal(html[i],html[0],`${copies[i]} must match index.html byte-for-byte`);
const app=html[0];
assert(app.includes('Zone Sketch by Will Flood v0.63'),'document title must be v0.63');
assert(app.includes('BETA v0.63'),'visible app badge must be v0.63');
assert(!app.includes('BETA v0.61'),'stale visible v0.61 badge remains');
assert(app.includes('id="buildModeBtn"'),'Drawing menu must ship the Build mode toggle');
assert(app.includes('function syncBuildMode()'),'Build mode UI sync must ship');
assert(app.includes('function setBuildMode(on)'),'Build mode state toggle must ship');
assert(app.includes('function combinedZoneAt(clientX,clientY)'),'combined zone hit logic must ship');
assert(app.includes("combinedZone:true"),'combined zone drag path must ship');
assert(app.includes("state.buildMode!==false"),'Build mode ON must remain the backwards-compatible default');
assert(app.includes('id="cbFloorSelect"'),'v0.61 multi-floor Circuit Builder must remain present');
assert(app.includes('function cbRepairConventionalRefs'),'v0.60 circuit recovery must remain present');
assert(app.includes('id="newProjectDialog"'),'new system project form must ship');
assert(app.includes('const SYSTEMS=Object.freeze('),'shared system registry must ship');
assert(['fire','security','cctv','access'].map(key=>app.indexOf('class="homeSystemTile" data-system="'+key+'"')).every((pos,i,a)=>pos>=0&&(i===0||pos>a[i-1])),'Home system tiles must be enabled and in approved order');
assert(!app.includes('isFuture')&&!app.includes('<small>Future</small>'),'all Home systems must be enabled');
assert(app.includes('id="cbBridgeToggle"'),'normal Circuit Builder must expose the Bridge toggle');
assert(app.includes('function cbBuildBridgeHits'),'normal Circuit Builder must record intentional crossing bridges');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(/versionCode\s+64\b/.test(gradle),'Android versionCode must be 64');
assert(/versionName\s+'0\.63'/.test(gradle),'Android versionName must be 0.63');
const beta=fs.readFileSync('beta.html','utf8');
assert(beta.includes('Web v0.63'),'beta portal must show Web v0.63');
assert(beta.includes('Android v0.63'),'beta portal must show Android v0.63');
assert(beta.includes('releases/download/v0.63/Zone-Sketch-by-Will-v0.63.apk'),'beta portal must target the v0.63 release asset');
assert(beta.includes('downloads/Zone-Sketch-by-Will-v0.63.apk'),'beta portal must retain the backup APK mirror');
assert(beta.includes('./web-v063.html'),'beta portal must open the fresh v0.63 launcher');
assert(beta.includes('FOUR SYSTEM PROJECTS'),'beta portal must describe the v0.63 milestone');
const download=fs.readFileSync('download.html','utf8');
assert.equal(download,beta,'download.html and beta.html should not drift');
const launcher=fs.readFileSync('web-v063.html','utf8');
assert(launcher.includes('index.html?pineapple=v063&fresh='),'fresh launcher must target the v0.63 cache key');
const regressions=fs.readFileSync('tests/run-regressions.cjs','utf8');
assert(regressions.includes("'system-modes'"),'four mode test must be in the full gate');
assert(regressions.includes("'floor-workflow-v061'"),'v0.61 floor regression must remain in the full gate');
assert(regressions.includes("'build-mode-v062'"),'v0.63 build-mode regression must be in the full gate');
assert(regressions.includes("'circuit-build-bridge-v062'"),'normal Circuit Builder bridge regression must be in the full gate');
console.log('PASS v0.63 release metadata, toggleable Zone Plan Build mode, regression parity and Android versioning');
