const fs=require('node:fs'),assert=require('node:assert/strict');
const copies=['index.html','ZoneSketch.html','Zone-Sketch-by-Will.html','app/src/main/assets/index.html'];
const html=copies.map(p=>fs.readFileSync(p,'utf8'));
for(let i=1;i<html.length;i++)assert.equal(html[i],html[0],`${copies[i]} must match index.html byte-for-byte`);
assert(html[0].includes('Zone Sketch by Will Flood v0.60'),'document title must be v0.60');
assert(html[0].includes('BETA v0.60'),'visible app badge must be v0.60');
assert(!html[0].includes('BETA v0.59'),'stale visible v0.59 badge remains');
assert(html[0].includes('function cbRepairConventionalRefs'),'circuit reference recovery must ship in v0.60');
assert(html[0].includes('function cbInvalidateSymbolIndex'),'symbol lookup invalidation must ship in v0.60');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(/versionCode\s+61\b/.test(gradle),'Android versionCode must be 61');
assert(/versionName\s+'0\.60'/.test(gradle),'Android versionName must be 0.60');
const beta=fs.readFileSync('beta.html','utf8');
assert(beta.includes('Web v0.60'),'beta portal must show Web v0.60');
assert(beta.includes('Android v0.60'),'beta portal must show Android v0.60');
assert(beta.includes('releases/download/v0.60/Zone-Sketch-by-Will-v0.60.apk'),'beta portal must target v0.60 release asset');
assert(beta.includes('downloads/Zone-Sketch-by-Will-v0.60.apk'),'beta portal must retain the backup APK mirror');
assert(beta.includes('./web-v060.html'),'beta portal must open the fresh v0.60 launcher');
const download=fs.readFileSync('download.html','utf8');
assert.equal(download,beta,'download.html and beta.html should not drift');
const launcher=fs.readFileSync('web-v060.html','utf8');
assert(launcher.includes('index.html?pineapple=v060&fresh='),'fresh launcher must target the v0.60 cache key');
console.log('PASS v0.60 release metadata, generated-copy parity, circuit recovery, portal links and Android versioning');
