const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{const server=http.createServer((q,r)=>{const path=(q.url||'/').split('?')[0],file=path==='/'?'index.html':path.slice(1);try{const data=fs.readFileSync(file);r.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.pdf')?'application/pdf':'text/html');r.end(data)}catch(e){r.statusCode=404;r.end('not found')}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({headless:true});try{const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];let name='School';p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept(d.type()==='prompt'?name:undefined));await p.goto('http://127.0.0.1:'+server.address().port);await p.locator('#homeNew').click();await p.locator('#projectsHome').waitFor({state:'hidden'});assert.notEqual(await p.evaluate(()=>document.activeElement.id),'site');
await p.locator('#surveyModeBtn').click();assert(await p.locator('.tools').isHidden());assert(await p.locator('#surveyTools').isVisible());assert.equal(await p.locator('#surveyMove').getAttribute('aria-pressed'),'true');assert.match(await p.locator('#surveyMove').innerText(),/Field grid/);assert(await p.locator('#surveySnap').isDisabled());assert.match(await p.locator('#surveySnap').innerText(),/Device snap · ON/);assert(await p.locator('#surveyUndo').isDisabled());
assert(await p.locator('#surveyRoom').isHidden());assert(await p.locator('#surveyNote').isHidden());let b=await p.locator('#canvas').boundingBox();
await p.locator('#surveyDevice').click();await p.locator('[data-symbol="smoke"]').click();await p.mouse.click(b.x+b.width*.5,b.y+b.height*.5);assert.equal(await p.locator('#surveyDevice').getAttribute('aria-pressed'),'true');
await p.locator('#surveyUndo').click();assert(await p.locator('#surveyUndo').isDisabled());await p.locator('#surveyMove').click();assert.equal(await p.locator('#surveyMove').getAttribute('aria-pressed'),'false');assert.match(await p.locator('#surveyMove').innerText(),/Grid hidden/);
await p.screenshot({path:'test-results/survey-mode-phone.png'});await p.setViewportSize({width:1024,height:768});await p.screenshot({path:'test-results/survey-mode-tablet.png'});await p.locator('#surveyModeBtn').click();assert(await p.locator('.tools').isVisible());
const home=async()=>{await p.locator('#projectMenuBtn').click();await p.locator('#homeBtn').click();await p.locator('#projectGrid .projectCard').first().waitFor()};const records=()=>p.evaluate(()=>new Promise(ok=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const q=r.result.transaction('draft').objectStore('draft').getAll();q.onsuccess=()=>ok(q.result.filter(x=>x?.project))}}));await home();const before=(await records())[0].updatedAt;
name='Warehouse';await p.locator('#homeNew').click();await p.locator('#projectsHome').waitFor({state:'hidden'});await home();await p.locator('#projectSearch').fill('school');await p.waitForTimeout(250);assert.equal(await p.locator('.projectCard').count(),1);await p.getByRole('button',{name:'Open',exact:true}).click();await p.locator('#projectsHome').waitFor({state:'hidden'});await p.reload();await p.locator('#resumeProject').click();assert.equal(await p.locator('#site').inputValue(),'School');assert.equal((await records()).find(x=>x.site==='School').updatedAt,before);assert.deepEqual(errors,[]);console.log('PASS: survey tools, constant field grid, room/undo, symbol placement, phone/tablet layout, project search, active project restore and stable edit time');}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
