const {chromium,webkit}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict');
(async()=>{
 let html=fs.readFileSync('index.html','utf8');
 const marker="document.querySelector('.app').inert=true;\nensureUiState();renderFloors();renderSymbolColors();syncSymbolScale();";
 assert(html.includes(marker));
 html=html.replace(marker,`window.eraseQA={seed:(survey=false)=>{resetInteraction();for(const k of ['walls','doors','windows','shutters','stairs','labels','symbols','pins','notes','shapes'])state[k]=[];state.locks={building:false,zones:false,background:false};state.layers={building:true,symbols:true,notes:true,zones:true,labels:true};state.walls=[.25,.5,.75].map((x,i)=>({id:'wall'+i,kind:'wall',points:[{x,y:.35},{x,y:.65}]}));state.walls.push({id:'untouched',kind:'wall',points:[{x:.2,y:.9},{x:.8,y:.9}]});if(survey){state.symbols=[.25,.5,.75].map((x,i)=>({id:'device'+i,type:'smoke',scope:'survey',x,y:.5,scale:1}));state.symbols.push({id:'plan-only',type:'panel',scope:'plan',x:.5,y:.5,scale:1})}setSurveyMode(survey);setTool('erase');undo=[];redo=[];changed()},read:()=>({walls:state.walls.map(o=>o.id),wallPoints:state.walls.map(o=>o.points),symbols:state.symbols.map(o=>o.id),undo:undo.length,redo:redo.length,pending:drawing?.refs?.size||0}),point:(x,y)=>{const p=screenPoint({x,y}),r=canvas.getBoundingClientRect();return{x:p.x+r.left,y:p.y+r.top}},protect:(kind)=>{if(kind==='locked')state.locks.building=true;else state.layers.building=false;draw()}};\n`+marker);
 const server=http.createServer((q,r)=>{const f=q.url.split('?')[0].slice(1);try{r.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.png')?'image/png':f.endsWith('.webp')?'image/webp':'text/html');r.end(f?fs.readFileSync(f):html)}catch{r.statusCode=404;r.end()}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const browser=await(process.env.PINEAPPLE_BROWSER==='webkit'?webkit:chromium).launch();
 try{for(const width of [390,1024]){
  const page=await browser.newPage({viewport:{width,height:844},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'Swipe QA':undefined));
  await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#homeNew').click();await page.locator('#newProjectName').fill('Swipe QA');await page.locator('#newProjectCreate').click();await page.locator('#projectsHome').waitFor({state:'hidden'});await page.locator('#zsSplash').waitFor({state:'hidden'});
  const seed=async(survey=false)=>{await page.evaluate(v=>eraseQA.seed(v),survey);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))};
  const read=()=>page.evaluate(()=>eraseQA.read()),point=(x,y)=>page.evaluate(([x,y])=>eraseQA.point(x,y),[x,y]);
  const swipe=async(y=.5)=>{const a=await point(.1,y),b=await point(.9,y);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:1});await page.mouse.up()};
  await seed();await page.locator('#deleteTop').click();const a=await point(.1,.5),b=await point(.9,.5);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:1});let r=await read();assert.equal(r.pending,3,'fast movement collects intermediate objects');assert.equal(r.walls.length,4,'preview does not mutate data');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForFunction(()=>{const c=document.querySelector('#canvas'),a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let red=0;for(let i=0;i<a.length;i+=4)if(a[i]>220&&a[i+1]<110&&a[i+2]<110)red++;return red>20},null,{timeout:5000});await page.screenshot({path:'test-results/swipe-delete-preview-'+width+'.png'});await page.mouse.up();r=await read();assert.deepEqual(r.walls,['untouched']);assert.equal(r.undo,1);
  await page.locator('#undoTop').click();assert.equal((await read()).walls.length,4);await page.locator('#redoTop').click();assert.deepEqual((await read()).wallPoints,[[{x:.2,y:.9},{x:.8,y:.9}]],'Redo preserves the untouched wall geometry');
  await seed();const tap=await point(.25,.5);await page.mouse.click(tap.x,tap.y);assert.equal((await read()).walls.length,3,'single tap still deletes one item');
  await seed();await swipe(.05);assert.equal((await read()).undo,0,'empty swipe creates no undo entry');
  for(const kind of ['locked','hidden']){await seed();await page.evaluate(k=>eraseQA.protect(k),kind);await swipe();assert.equal((await read()).walls.length,4);assert.equal((await read()).undo,0)}
  for(const abort of ['pointercancel','lostpointercapture','blur','second-finger']){
   await seed();await page.evaluate(abort=>{const c=document.querySelector('#canvas'),capture=c.setPointerCapture;c.setPointerCapture=()=>{};const a=eraseQA.point(.1,.5),b=eraseQA.point(.9,.5);const fire=(type,id,p)=>c.dispatchEvent(new PointerEvent(type,{pointerId:id,pointerType:'touch',clientX:p.x,clientY:p.y,bubbles:true}));try{fire('pointerdown',11,a);fire('pointermove',11,b);if(abort==='blur')window.dispatchEvent(new Event('blur'));else if(abort==='second-finger')fire('pointerdown',12,a);else fire(abort,11,b);fire('pointerup',11,b);if(abort==='second-finger')fire('pointerup',12,a)}finally{c.setPointerCapture=capture}},abort);assert.equal((await read()).walls.length,4,abort+' keeps data intact');assert.equal((await read()).undo,0);
  }
  await seed(true);await page.locator('#surveyDelete').click();await page.evaluate(()=>{const c=document.querySelector('#canvas'),capture=c.setPointerCapture;c.setPointerCapture=()=>{};const a=eraseQA.point(.1,.5),b=eraseQA.point(.9,.5);try{for(const [type,p] of [['pointerdown',a],['pointermove',b],['pointerup',b]])c.dispatchEvent(new PointerEvent(type,{pointerId:21,pointerType:'touch',clientX:p.x,clientY:p.y,bubbles:true}))}finally{c.setPointerCapture=capture}});r=await read();assert.deepEqual(r.symbols,['plan-only'],'Survey removes only visible Survey devices');assert.equal(r.walls.length,4,'Survey protects building geometry');assert.equal(r.undo,1);await page.locator('#surveyUndo').click();assert.equal((await read()).symbols.length,4);await page.locator('#surveyRedo').click();assert.deepEqual((await read()).symbols,['plan-only']);assert.deepEqual(errors,[]);await page.close();console.log('PASS swipe deletion, one-step undo/redo, preview, locks, hidden layers, interruptions and Survey at '+width);
 }}finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exit(1)});
