const {chromium}=require('playwright');
const fs=require('node:fs');
const http=require('node:http');
const assert=require('node:assert/strict');
const {createHash}=require('node:crypto');
const assets=[['fire','Fire','home-system-fire.webp','5a127602de4fd89ad2652c6b7e7ef02ac4eda0b573ab5b0e55068c85ff25d6d7'],['security','Security','home-system-intruder.webp','035dc248cc2d0cc1fdecdac1ea2bf5a47a8e3fe1c1f67fbbb16601d1d2bc2a60'],['cctv','CCTV','home-system-cctv.webp','2a7142bc89e458bc157259049d3f6c565b55514f19f4ab8f16e0a3e0bb37af3c'],['access','Access Control','home-system-access-control.webp','69d834063f17da0b7faaed01196081cdd85512d8652ec0dccd5874fa6693f258']];
for(const [, ,file,hash] of assets){const original=fs.readFileSync('assets/'+file),mirror=fs.readFileSync('app/src/main/assets/assets/'+file);assert.equal(createHash('sha256').update(original).digest('hex'),hash);assert.deepEqual(mirror,original)}
const server=http.createServer((req,res)=>{const path=decodeURIComponent((req.url||'/').split('?')[0]);try{const file=path==='/'?'index.html':path.slice(1);const data=fs.readFileSync(file);res.setHeader('Content-Type',file.endsWith('.webp')?'image/webp':file.endsWith('.js')?'text/javascript':'text/html');res.end(data)}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');
(async()=>{await new Promise(ok=>server.once('listening',ok));const browser=await chromium.launch({headless:true});try{const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.AndroidBridge={shareFile:(data,name,mime)=>window.shared={data,name,mime}}});await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>!document.querySelector('#homeNew').disabled);
const tiles=p.locator('.homeSystemPreview .homeSystemTile');assert.equal(await tiles.count(),4);assert.equal(await p.locator('.homeSystemPreview .isFuture,[aria-disabled="true"]').count(),0);
for(let i=0;i<4;i++){const [key,label,file]=assets[i],tile=tiles.nth(i);assert.equal(await tile.getAttribute('data-system'),key);assert.equal((await tile.locator('b').textContent()).trim(),label);assert((await tile.locator('img').getAttribute('src')).endsWith(file));assert(await tile.locator('img').evaluate(img=>img.complete&&img.naturalWidth===96&&img.naturalHeight===96&&getComputedStyle(img).filter==='none'))}
const home=async()=>{await p.evaluate(()=>document.querySelector('#headerHomeBtn').click());await p.locator('#projectsHome').waitFor({state:'visible'})};
const record=async site=>p.evaluate(async site=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const r=db.transaction('draft').objectStore('draft').openCursor();r.onsuccess=()=>{const c=r.result;if(!c){ok(null);return}if(String(c.key).startsWith('project:')&&c.value.site===site){ok(c.value);return}c.continue()};r.onerror=()=>no(r.error)})},site);
const card=site=>p.locator('.projectCard').filter({has:p.getByRole('heading',{name:site,exact:true})});
for(const [key,label] of assets){const site='Mode '+label;await p.locator('.homeSystemTile[data-system="'+key+'"]').click();assert(await p.locator('#newProjectDialog').isVisible());assert.equal(await p.locator('.newProjectChoice[aria-pressed="true"]').getAttribute('data-system'),key);assert.equal(await p.locator('#newProjectCreate').textContent(),'Create '+label+' Project');assert(await p.locator('#newProjectCreate').isDisabled());await p.locator('#newProjectName').fill(site);await p.locator('#newProjectCreate').click();await p.locator('#projectsHome').waitFor({state:'hidden'});assert(await p.locator('#canvas').isVisible());assert.equal((await p.locator('#editorSystemIdentity').innerText()).trim(),label);await p.waitForFunction(()=>document.querySelector('#saveIndicator').textContent.startsWith('Saved'));assert.equal((await record(site)).project.systemType,key);await home();assert.equal((await card(site).locator('.projectIdentity').innerText()).trim(),label)}
await p.reload();await p.waitForFunction(()=>!document.querySelector('#homeNew').disabled);for(const [key,label] of assets){const site='Mode '+label;assert.equal((await card(site).locator('.projectIdentity').innerText()).trim(),label);await card(site).getByRole('button',{name:'Open',exact:true}).click();await p.locator('#projectsHome').waitFor({state:'hidden'});assert.equal((await p.locator('#editorSystemIdentity').innerText()).trim(),label);assert(await p.locator('#canvas').isVisible());await home()}
await card('Mode Security').getByRole('button',{name:'Duplicate'}).click();await card('Mode Security (copy)').waitFor();assert.equal((await record('Mode Security (copy)')).project.systemType,'security');
await card('Mode CCTV').getByRole('button',{name:'Export'}).click();await p.waitForFunction(()=>!!window.shared);const backup=await p.evaluate(()=>JSON.parse(atob(window.shared.data.split(',')[1])));assert.equal(backup.project.systemType,'cctv');await p.locator('#projectFile').setInputFiles({name:'mode.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await p.locator('#projectsHome').waitFor({state:'hidden'});assert.equal((await p.locator('#editorSystemIdentity').innerText()).trim(),'CCTV');await home();assert.equal(await card('Mode CCTV').count(),2);
// Seed a pre-upgrade project with representative nested data and no system field.
const old=(await record('Mode Fire'));await p.evaluate(old=>new Promise((ok,no)=>{delete old.systemType;delete old.project.systemType;old.project.floors[0].data.notes.push({id:'legacy-note',x:.2,y:.3,text:'Existing detail'});old.project.floors[0].data.circuits.push({id:'legacy-circuit',name:'Original route',legs:[]});old.project.floors[0].data.pins.push({id:'legacy-pin',x:.4,y:.5,kind:'note',text:'Photo survey marker'});const r=indexedDB.open('ZoneSketch-v1',1);r.onsuccess=()=>{const tx=r.result.transaction('draft','readwrite');tx.objectStore('draft').put(old,'project:'+old.id);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)};r.onerror=()=>no(r.error)}),old);
await p.reload();await p.waitForFunction(()=>!document.querySelector('#homeNew').disabled);assert.equal((await card('Mode Fire').locator('.projectIdentity').innerText()).trim(),'Fire');await card('Mode Fire').getByRole('button',{name:'Open',exact:true}).click();await p.locator('#projectsHome').waitFor({state:'hidden'});assert.equal((await p.locator('#editorSystemIdentity').innerText()).trim(),'Fire');const migrated=await record('Mode Fire');assert.equal(migrated.project.systemType,'fire');assert.equal(migrated.project.floors[0].data.notes[0].text,'Existing detail');assert.equal(migrated.project.floors[0].data.circuits[0].id,'legacy-circuit');assert.equal(migrated.project.floors[0].data.pins[0].id,'legacy-pin');await home();
for(const [width,height] of [[320,568],[390,844],[430,932],[768,1024],[1280,800]]){await p.setViewportSize({width,height});await p.locator('#homeNew').click();await p.locator('#newProjectName').fill('Viewport check');const panel=await p.locator('#newProjectPanel').boundingBox();assert(panel.x>=0&&panel.x+panel.width<=width+1&&panel.y>=0&&panel.y+panel.height<=height+1,`panel outside ${width}x${height}`);await p.locator('#newProjectCreate').scrollIntoViewIfNeeded();const create=await p.locator('#newProjectCreate').boundingBox();assert(create.y>=0&&create.y+create.height<=height+1,`Create obscured at ${width}x${height}`);await p.locator('#newProjectClose').click();assert(await p.locator('#newProjectDialog').isHidden());assert(await p.locator('#homeNew').isVisible())}
assert.deepEqual(errors,[]);console.log('PASS: four system modes, legacy migration and data, reload, duplicate, export/import, exact assets, shared editor, five viewport sizes');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exit(1)});
